### ISSUE TITLE
Stored-procedure level interface for sql transport

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#102]

**Comment by SimonCropp** [comment]
why is this in required for async/await support #100 ?

**Comment by weralabaj** [comment]
@SimonCropp It's not required, it's related but new Sql transport can be released without that feature. Similar to all issues listed in # 100 as "related".

**Comment by SzymonPobiega** [comment]
I still think we should do it. The sql transport runtime should only depend on the presence of two SPs
`Receive` and `Send`. The installers should take care of creating these SPs. This way we enable people to fine-tune the behavior. Also, this would allow to run on other RDBMS if people provide proper SPs that have the same signature.

**Comment by MarcinHoppe** [comment]
@SzymonPobiega IMO, this is a double edged sword: currently if we have a bug or want to make an improvement, we fix the embedded SQL and ship a new NuGet. If these were SPs, either the endpoint would have to run under account with enough privileges to modify the database schema (not a good idea) or users would have to update the schema along with updating a NuGet.

BTW, right now there would have to be more SPs: `Peek`, `Receive`, `Send`, `Purge` and `Purge expired`.

**Comment by SimonCropp** [comment]
in terms of us creating sprocs as part of an install. please consider the upgrade story when we want to change those sprocs. Also consider that a clients DBA may have customised those sprocs

**Comment by SimonCropp** [comment]
also consider the competing consumer model... ie when is the sproc changes when two different versions may have assumptions on a specific iteration of a sproc

**Comment by danielmarbach** [comment]
I think this is very dangerous. We open up a can of worms which we can no longer contain.

**Comment by MarcinHoppe** [comment]
I agree with @danielmarbach. It seems to me, however, that the issue keeps popping up again and again.

I think we should consider forming a TF to discuss pros and cons, make a decision and document it properly.

**Comment by SzymonPobiega** [comment]
Based on @SimonCropp and @danielmarbach feedback, closing this one as a bad idea.
