### ISSUE TITLE
Spike for multi-db support using merge replication

### ISSUE THREAD

**Issue by weralabaj** [Particular/NServiceBus.SqlServer#103]
Connects to #100

**Goal:**
Use merge replication to provide multi-database support for SqlTransport.

https://msdn.microsoft.com/en-us/library/ms152746.aspx
https://technet.microsoft.com/en-us/library/ms151819(v=sql.105).aspx

**Expected outcomes:**
- Easier configuration for SqlTransport
- Safer connection management (connections shared for reading, not writing to another db)
- Making transport less smart than it is now (smart transports caused us trouble already)
- Works with SC and is backwards compatible (v1, v2)
- If necessary, define what tools we'd need to provide (e.g. scripts, docos, etc.)

**Timebox:**
(days, people-days, deadline for presenting results?)
How about let's meet next Monday and see what we got by then?

**Comment by weralabaj** [comment]
//cc: @tmasternak @SzymonPobiega @andreasohlund @mauroservienti Feel free to clarify if I forgot sth.

**Comment by johnsimons** [comment]
I have just watched the meeting regarding this and I wonder if we jumping too quickly to a solution ?

**Comment by weralabaj** [comment]
@johnsimons Do you have some alternatives in mind? I thought that this suggestion is based on previous discussions (e.g. from Budapest), so seemed like it's well thought ;)
Either way, please share your thoughts!

**Comment by tmasternak** [comment]
I think we can close this. Merge replication will not suit our goals as it does not have a transactional behavior. The synchronization between db's is performed is scheduled by external agent. /cc: @mauroservienti  @weralabaj

**Comment by mauroservienti** [comment]
agree to close
