### ISSUE TITLE
Backwards compatibility testing scenarios

### ISSUE THREAD

**Issue by weralabaj** [Particular/NServiceBus.SqlServer#110]
### Compatibility Tests:
- [x]  Scenarios
 - [x] Simple send
 - [x] Response/Reply
 - [x] Pub/Sub
- [x] Configuration variations
 - [x] Versions 1, 2 and 3
 - [x] Single, multischema ~~and multidatabase~~
 - [x] Scale-out
- [x] Callbacks
 - [x] Simple
 - [x] Scale-out
- [x] Incompatible v2 config
- [x] Persistence. Sharing connections/transactions
 - Sagas
- [x] 3rd party integration - verify nothing changed
- [x] ServiceControl https://github.com/Particular/ServiceControl/issues/609

**Comment by petersgiles** [comment]
@weralabaj how can I help?

**Comment by tmasternak** [comment]
@weralabaj  @mauroservienti  I propose to remove the performance tests from the scope of this task. It depends on Particular/ProductionTests#33 and should be implemented after we figure out what performance tests should look like.

**Comment by mauroservienti** [comment]
+1, we can be chickens if required.

**Comment by tmasternak** [comment]
Created a new tasks for performance testing Particular/NServiceBus.SqlServer/issues/125

**Comment by tmasternak** [comment]
This one is currently blocked until NHibernate is ready for wire-compat testing
