### ISSUE TITLE
Single-db, multi-schema Request/Response requires unnecessary coupling

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#116]
Currently in v1 and v2, requests do not include schema information. As a result when sender and receiver have input queues in separate schemas receiver needs a piece of configuration (file or api) which specifies sender' schema name.

This introduces unneeded coupling and requires knowing all senders that will participate in Request/Response MEP at receiver's configuration time.

**Comment by SzymonPobiega** [comment]
We're unlikely to add features to V1 and V2. Closing.
