### ISSUE TITLE
Single-db, multi-schema Pub/Sub requires unnecessary coupling

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#117]
### Problem

In version 2 subscription messages do not contain schema information. This causes problems for subscribers that have their queues stored in non-default schemas. In such scenario it is necessary for publisher to provide via configuration a schema information for each subscriber. This introduces coupling that should not be needed for pub-sub message exchange.
### Assumptions and Constrains
- The coupling mentioned above exists also in other scenarios e.g request-response but solving those is not ins scope of this issue.
- The solution should be both backwards and forward compatible. Next minor release of 2.x solving this problem will work both with [1-2.x) as well as [3,) endpoints. What it means more specifically is that 2.x will work with [1-2.x) and [3,) in any pub-sub scenario acting both as subscriber and the publisher. This will also require following transport address structure introduced in v3 which is `queuename@[schema]`.
- If a users decides to upgrade endpoint running with lower versions than 2.x which is a publisher we should allow for such scenario.
- The solution should work with any persistence storage (NHibernate, InMemory, Raven etc.)

**Comment by elovelan** [comment]
I'm about to start developing a fix for this but I want to confirm that it's not already being worked on.

**Comment by tmasternak** [comment]
Hi Eric, nobody is working on that on our end. That being said we had some initial discussions on possible approach to solving that. So far it looks that changes will be mainly around supporting schema information in the physical address that is sent in subscription messages. 

Two additional aspects to have in mind are: 

* backwards compatibility ([compatibility tests](https://github.com/Particular/EndToEnd/tree/master/src/TransportCompatibilityTests) should be useful for checking that) 
* migration path for v2 endpoints that are publishing events and we want to apply fix to. If we go with extending physical address approach we need to migrate the addresses already in the subscription storage.

If you find it helpful I can provide more details in the issue.

**Comment by elovelan** [comment]
More details are always helpful :smile:

I have a good understanding of the issue as I've written some rather hacky code to work around it.

Regarding backwards compatibility, I'm not sure how I can guarantee that said hacked-together solutions (e.g. using custom pipeline behaviors) would continue to work. Otherwise I'll be sure to maintain compatibility. Any recommendations for the former?

**Comment by tmasternak** [comment]
@elovelan I've updated the issue description.

By compatibility I meant making sure the new minor of 2 will work fine with previous versions as well as version 3.

**Comment by SzymonPobiega** [comment]
We're unlikely to add features to V1 and V2. Closing.
