### ISSUE TITLE
Support additional SQL dialects

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.SqlServer#1216]
#### Describe the requested feature

While the SQL Persistence package supports a wide range of SQL engines, the SQL transport package is currently tied to Microsoft SQL Server. This can be a significant adoption burden or unnecessary infrastructure requirement when there is already existing SQL infrastructure using a different engine (e.g. PostgreSQL). Additionally, this also has significant cost impacts as MSSQL server licensing might become much more pricey than comparable alternatives (regardless of on-premises or cloud-hosted offerings).
        
#### Describe alternatives you've considered

* PostgreSQL and MySQL are the two most popular SQL servers at the moment, according to the [2023 StackOverflow Developer Survey](https://survey.stackoverflow.co/2023/#most-popular-technologies-database-prof).
* [Babelfish](https://learnsql.com/blog/what-sql-dialect-to-learn/) is a project focused on migrating from MSSQL to PostgreSQL.

**Comment by poornimanayar** [comment]
Hi Tim,

We are in the process of releasing a version of PostgreSQL Transport https://github.com/Particular/NServiceBus.SqlServer/issues/1364

Poornima

**Comment by SzymonPobiega** [comment]
Single we support PostgreSQL already, closing this issue.
