### ISSUE TITLE
Investigate if we still need Secondary Receivers

### ISSUE THREAD

**Issue by weralabaj** [Particular/NServiceBus.SqlServer#124]
Connects to #100 

As the solution for the https://github.com/Particular/NServiceBus.RabbitMQ/issues/35, to prevent message duplication we introduced "Secondary Receivers". That was dealing both with pubsub and callbacks.
That solution was then copied to SqlServer. We think that we no longer need it in SqlServer, because the issue was mitigated with the new callbacks implementation. However, we still need secondary receivers in Rabbit transport, as they're also used in pubsub.
The point of this task is to investigate the changes in both solutions, analyze current implementation in core and either confirm or deny the stated assumptions.

**Comment by tmasternak** [comment]
After doing investigation it looks that we do not need secondary receiver in SqlTransport. New scale-out model assumes queue-per-instance.

@weralabaj @mauroservienti I think we can close this one and open a more specific issue in [RabbitMQ](https://github.com/Particular/NServiceBus.RabbitMQ) repository.

**Comment by mauroservienti** [comment]
> New scale-out model assumes queue-per-instance.

Can you give me more details? Is competing consumers still supported?

**Comment by tmasternak** [comment]
My understanding is this:
* We support competing-consumers and queue-per-instance but callbacks work only with the second approach
* If somebody needs to to support competing-consumers and callbacks (e.g. scaled-put web front-end) s/he needs to setup a second endpoint instance just for that. We will provide necessary doco.

/cc @SzymonPobiega @andreasohlund

**Comment by SzymonPobiega** [comment]
:+1:

**Comment by SzymonPobiega** [comment]
@tmasternak did you figure out why do we have these additional receivers in Rabbit?

**Comment by tmasternak** [comment]
It is no confirmed yet. There is an issue in RabbitMQ repository for that. But it looks that I solves the duplicate event delivery in scale-out deployment.

**Comment by mauroservienti** [comment]
Lovely.

> We support competing-consumers and queue-per-instance but callbacks work only with the second approach

thanks @tmasternak

**Comment by tmasternak** [comment]
closing
