### ISSUE TITLE
Eliminate hardcoded connection strings from acceptance tests

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.SqlServer#127]
Several acceptance tests have their connection string hardcoded to a local instance of SQL Express:
- When_using_custom_connection_factory.cs
- When_a_corrupted_message_is_received.cs

This makes it impossible to run these tests against a different SQL Server instance (e.g. LocalDB).

Majority of acceptance tests executed with this transport can be configured via `SqlServerTransport.ConnectionString` environment variable and can be executed against any SQL Server instance.

**Comment by weralabaj** [comment]
@MarcinHoppe Are you going to work on that or can that be grabbed by anybody?

**Comment by MarcinHoppe** [comment]
@weralabaj I have an idea for a fix but it is totally up for grabs by anybody.

**Comment by MarcinHoppe** [comment]
Resolved by #391
