### ISSUE TITLE
Documentation for v3: Upgrade guide

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.SqlServer#134]
Task force: @tmasternak @weralabaj @justabitofcode @mauroservienti

Plan of attack:
 1. [ ] Configuration api changes for multi-schema
 2. [ ] Configuration api chagnes for providing custom connection string
 3. [ ] Changes in multi-db support
 4. [ ] Document new shutdown timeout behavior for SQL Particular/NServiceBus.Host#51
 5. [ ] Document new shutdown timeout behavior for MSMQ 

Related to #100

http://docs.particular.net/nservicebus/upgrades/5to6

**Comment by weralabaj** [comment]
I'm moving this to the doco repo
