### ISSUE TITLE
Documentation for v3: Multi-schema v3 to v1-2 setup guide

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.SqlServer#135]
Task force: @tmasternak @weralabaj @justabitofcode @mauroservienti

Related to #100

**Comment by SimonCropp** [comment]
@mauroservienti should this be in docs? and what does "Multi-schema v3 to v1-2 setup guide" mean?

**Comment by mauroservienti** [comment]
good point @SimonCropp 

> and what does "Multi-schema v3 to v1-2 setup guide" mean?

I don't know :)
Moved to https://github.com/Particular/docs.particular.net/issues/1152
