### ISSUE TITLE
Documentation for v3: docu pages

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.SqlServer#137]
Task force: @tmasternak @weralabaj @justabitofcode @mauroservienti

Related to #100

* [x] [1](http://docs.particular.net/nservicebus/sqlserver/)
* [x] [Concurrency model](http://docs.particular.net/nservicebus/sqlserver/concurrency) -  [PR in Docs](https://github.com/Particular/docs.particular.net/pull/1091)
* [ ] [3. Multi-database](http://docs.particular.net/nservicebus/sqlserver/multiple-databases)
* [x] [4](http://docs.particular.net/nservicebus/sqlserver/operations-scripting)
* [x] [5?](http://docs.particular.net/nservicebus/sqlserver/usage)

**Comment by tmasternak** [comment]
@mauroservienti @justabitofcode I think that [3](http://docs.particular.net/nservicebus/sqlserver/multiple-databases) and [5?](http://docs.particular.net/nservicebus/sqlserver/usage) will need to change because of the changes in multi-db setup

**Comment by weralabaj** [comment]
https://github.com/Particular/docs.particular.net/issues/1152 and https://github.com/Particular/docs.particular.net/issues/1103 cover multi-database updates in v3, so this issue can be closed.
