### ISSUE TITLE
SQL Server transport stops delivering delayed messages

### ISSUE THREAD

**Issue by crirusu** [Particular/NServiceBus.SqlServer#1395]
#### Description
When items cannot be taken out from the Delayed queue multiple times - we have this error, and messages will never be moved unless we restart the service.

```txt
Message: Exception thrown while moving matured delayed messages
Exception: The value needs to be either -1 (signifying an infinite timeout), 0 or a positive integer. (Parameter 'millisecondsDelay')
Stack trace: 
at NServiceBus.Transport.Sql.Shared.DelayedDelivery.BackOffStrategy.WaitForNextExecution(CancellationToken cancellationToken)
   at NServiceBus.Transport.Sql.Shared.PubSub.DueDelayedMessageProcessor.MoveMaturedDelayedMessagesAndSwallowExceptions(CancellationToken moveDelayedMessagesCancellationToken)
```

I think you should check waitTime below.

```csharp
public async Task WaitForNextExecution(CancellationToken cancellationToken = new())
{
        CalculateNextExecutionTime();

        // While running this loop, a new delayed message can be stored
        // and NextExecutionTime could be set to a new (sooner) time.
        while (DateTime.UtcNow < NextExecutionTime)
        {
            int waitTime = (int)(NextExecutionTime - DateTime.UtcNow).TotalMilliseconds;
            waitTime = waitTime < 1000 ? waitTime : 1000;
            await Task.Delay(waitTime, cancellationToken).ConfigureAwait(false);
        }
        NextExecutionTime = DateTime.MaxValue;
}
```

#### Expected behavior

Messages should be extracted back to the original queue.

#### Actual behavior

Messages remain stucked in .Delayed queue.

#### Versions
  <PackageReference Include="Npgsql" Version="8.0.3" />
  <PackageReference Include="NServiceBus" Version="9.0.3" />
  <PackageReference Include="NServiceBus.Extensions.Hosting" Version="3.0.0" />
  <PackageReference Include="NServiceBus.Persistence.Sql" Version="8.1.0" />
  <PackageReference Include="NServiceBus.Transport.PostgreSql" Version="8.1.2" />  

### Steps to reproduce

Send some messages to the .Delayed queue.
Simulate a timeout when retrieving messages from the .Delayed.
Let it run like this for hours until the delay > int.MaxValue

**Comment by mauroservienti** [comment]
Thanks for raising this, @crirusu.

Can you please share with us what version of NServiceBus and Sql Transport you are using?
Second question: are you using the SQL Server flavor or the PostgreSQL one?

**Comment by validide** [comment]
@mauroservienti the project is using the PostgreSQL transport with the following versions:

```
NServiceBus-> 9.1.0
NServiceBus.Extensions.Hosting-> 3.0.0
NServiceBus.Persistence.Sql-> 8.1.0
NServiceBus.Transport.PostgreSql-> 8.1.2

```

**Comment by johnsimons** [comment]
@validide @crirusu,

When you say 
> Let it run like this for hours until the delay > int.MaxValue

What do you mean? I don't think this condition can ever be true. Can you clarify?

**Comment by validide** [comment]
Hi,

I have not looked into this miself and Cristina is out for a couple of days but I will try to give a bit of a context:

We were trying to run NServiceBus on AWS Aurora Serverles. During the night when the environment has little trafic and the database scales down it seems we end-up in a loop where all the calls to the delayed queues timeout.

One thing we tried to avoid the timeouts was to reduce the batch size. We tried with 10 and then 1 items but we had no success. 

I think I saw a similar issue posted here but I do not find it now.

**Comment by nshift-diva** [comment]
I think it was this issue I stubble upon https://github.com/Particular/NServiceBus.SqlServer/pull/1392

**Comment by jpalac** [comment]
A fix will be released in NServiceBus.SqlServer 8.1.3

**Comment by abparticular** [comment]
@crirusu @validide @nshift-diva @PhilAch 

The fix is now available - https://github.com/Particular/NServiceBus.SqlServer/releases/tag/8.1.3

**Comment by validide** [comment]
We will update today/tomorrow and see.

**Comment by validide** [comment]
@abparticular, it seems the issue has been fixed, at least for out case.

Thank you!
