### ISSUE TITLE
Max Pool Size for NSB with Postgres

### ISSUE THREAD

**Issue by crirusu** [Particular/NServiceBus.SqlServer#1411]
#### Description
When we run NSB with a connection string without specifying Max Pool Size we receive the following warning:
conn string exanple : 
Host=myHost;Port=3306;Database=myDb;Username=myDbUser;Password=xxx;SslMode=Prefer;Trust Server Certificate=true;Include Error Detail=true;Connection Idle Lifetime=30

"Maximum connection pooling value (Max Pool Size=N) is not configured on the provided connection string. The default value (100) will be used."

When we try to setup Max Pool Size with a connection string like this:
Host=myHost;Port=3306;Database=myDb;Username=myDbUser;Password=xxx;SslMode=Prefer;Trust Server Certificate=true;Include Error Detail=true;Max Pool Size=20;Connection Idle Lifetime=30

the service cannot start - Hosting failed to start

![image](https://github.com/user-attachments/assets/c4efdfcb-caf4-49d4-9464-400919ea98ef)

In the code you check for Max Pool Size, but postgresl is using Maximum

https://www.npgsql.org/doc/connection-string-parameters.html

#### Expected behavior
 Use the Maximum Pool Size 
#### Versions

  <PackageReference Include="NServiceBus" Version="9.1.1" />
  <PackageReference Include="NServiceBus.Extensions.Hosting" Version="3.0.0" />
  <PackageReference Include="NServiceBus.Persistence.Sql" Version="8.1.0" />
  <PackageReference Include="NServiceBus.Transport.PostgreSql" Version="8.1.3" />

### Steps to reproduce

Use the connection string above without setting any pool siize - start the service => Warning
Use the connection string with Max Pool Size => the service won't start.

**Comment by SzymonPobiega** [comment]
Hi!

Thanks for reporting it. It looks like a bug that is related to sharing some of the codebase with SQL Server variant of the transport. We'll take care of it in the next release.

**Comment by rob-johnson-1978** [comment]
@SzymonPobiega as per [discuss issue](https://discuss.particular.net/t/postgres-sql-persistence-or-postgres-transport-erroneous-warning/4083/6) I was asked to raise this too - didn't realise it was already raised, apologies. I've closed [my issue](https://github.com/Particular/NServiceBus.SqlServer/issues/1417).

**Comment by jpalac** [comment]
Released in [8.1.4](https://github.com/Particular/NServiceBus.SqlServer/releases/tag/8.1.4)
