### ISSUE TITLE
NServiceBus.Transport.PostgreSql expects connection string parameter `Max Pool Size` but that is not valid for PostgreSQL

### ISSUE THREAD

**Issue by rob-johnson-1978** [Particular/NServiceBus.SqlServer#1417]
#### Description
The [ConnectionPoolValidator](https://github.com/Particular/NServiceBus.SqlServer/blob/master/src/NServiceBus.Transport.Sql.Shared/Configuration/ConnectionPoolValidator.cs) in `NServiceBus.Transport.Sql.Shared` returns `ValidationCheckResult.Invalid(ConnectionPoolSizeNotSet);` if the parameter `Max Pool Size` isn't present. 

To the best of my knowledge/Googling, the parameter `Max Pool Size` is only for MSSQL. The appropriate parameter for Postgres is `MaxPoolSize` (no spaces). This is borne out by the below error when using `Max Pool Size` in the connection string with and `NpgsqlConnection`:

```
An exception of type System.ArgumentException was thrown: Couldn't set max pool size (Parameter 'max pool size')   InnerException of type System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.      at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value)\n   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)\n   at Npgsql.NpgsqlConnectionStringBuilder..ctor(String connectionString)\n   at Npgsql.NpgsqlConnection.SetupDataSource()\n   at Npgsql.NpgsqlConnection.set_ConnectionString(String value)\n   at Npgsql.NpgsqlConnection..ctor(String connectionString)\n
```

#### Expected behavior
Validate against `MaxPoolSize` and `Maximum Pool Size` when Postgres (both are valid).

#### Actual behavior
Validates against `Max Pool Size` regardless of database type (I think / assume)

#### Versions
Not 100% sure, but I'm using `NServiceBus.Transport.PostgreSql` version `8.1.3` which uses `Npgsql` version `8.0.3`. I can also reproduce the above error (not the warning from NSB) when using this version of `Npgsql` on its own. 

### Steps to reproduce

1. Create a host application using `NServiceBus.Transport.PostgreSql` 8.1.3
2. Use a connection string which has `Max Pool Size=N` instead of `MaxPoolSize=N` or `Maximum Pool Size=N`
3. Start the application
4. It should log the following warning: `Maximum connection pooling value (Max Pool Size=N) is not configured on the provided connection string. The default value (100) will be used.`

### Relevant log output

```shell
`Maximum connection pooling value (Max Pool Size=N) is not configured on the provided connection string. The default value (100) will be used.`
```

#### Workarounds
Presumably there is no workaround - however, as this is only a warning, from what I can see it's not affecting functionality.

#### Possible solutions
Create a Postgres-specific validator in `NServiceBus.Transport.PostgreSql`, an MSSQL one in `NServiceBus.Transport.SqlServer` and get rid of the shared one that's giving this warning.

#### Additional information
N/a

**Comment by SzymonPobiega** [comment]
Duplicate of https://github.com/Particular/NServiceBus.SqlServer/issues/1411
