### ISSUE TITLE
Add support for batched inserts

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.SqlServer#143]
If Unit of Work for bus session ends up being supported in core we should add support to it adding specific transport feature such as, but not only, bulk inserts.

Related to: https://github.com/Particular/NServiceBus/pull/3355

**Comment by tmasternak** [comment]
I think that we can add that in v3.x - there are no compatibility problems. I would suggest to not do it for legacy multi-instance mode (introduces significant complexity as we need to batch per destination sql instnace).

**Comment by mauroservienti** [comment]
> I think that we can add that in v3.x - there are no compatibility problems.

:+1: 

> I would suggest to not do it for legacy multi-instance mode (introduces significant complexity as we need to batch per destination sql instnace).

:+1:

**Comment by mauroservienti** [comment]
Supported via https://docs.particular.net/transports/sql/transactions#user-provided-transactions
