### ISSUE TITLE
Support multi-catalog deployments 

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#149]
Version 3 of SqlTransprort supports only multi-schema setup. It should be possible to add multi-catalog support as well. 

See Particular/NServiceBus.SqlServer#139 for more details
Inception: https://github.com/Particular/CustomerSuccess/issues/166

**Comment by mauroservienti** [comment]
As discussed this morning the `catalog` name should be part of the endpoint address as it is for the schema name in 3.0

**Comment by ramonsmits** [comment]
Should support both: `userdb.dbo` and also `[userdb].[dbo]` to also supports dots in catalogs and/or schemas.

**Comment by SzymonPobiega** [comment]
I am not convinced here. Single even SQL 2016 does not support cross-catalog transactions in AlwaysOn mode, catalog seems to be something physical rather than logical. I'd rather put the catalog/database in same bucket as SQL server instances and handle it similarly to RabbitMQ shovel plugin.

**Comment by mauroservienti** [comment]
@szymonpobiega here you are sir https://github.com/Particular/NServiceBus.SqlServer/issues/146

And you have a good point, @tmasternak let's review this in light of that.

**Comment by SzymonPobiega** [comment]
Here's the article that describes AlwaysOn vs cross-catalog transactions: https://technet.microsoft.com/en-us/library/ms366279(v=sql.130).aspx. My understanding is `not supported` but the wording is a bit confusing. Should we try it and verify?

**Comment by tmasternak** [comment]
I think that we should try a spike and verify our assumptions.

**Comment by MarcinHoppe** [comment]
Spike issue has been created: #325.

**Comment by SzymonPobiega** [comment]
Fixed by #330
