### ISSUE TITLE
Check the round-robin behavior in scale-out

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#154]
taskforce: @tmasternak

## Goal
We need to verify that enpdoint instance load-balancing with competing consumers works as expected i.e. that load sharing is fair 'enough'. In scope of this issue we should write a sample or scaled-out endpoint that will check that over longer period of time the message sharing is balanced.

## Test Scenario

I've run a simple test scenario:
  * Single shared database
  * Two endpoints: `Sender` and `Receiver`
  * `Receiver` consisted of two processes sharing single input queue (competing-consumers)
  * `Sender` was sending 10, 100, 1000 and 10000 messages. For each message number the test was run 5 times. 
  * I've calculated average imbalance for each message number. I defined it as the normalized difference between number of messages consumed by two receiving processes. So imbalance=0 means that messages are shared 50%-50% and 1 means that single receiver gets all messages.

## Results

![image](https://cloud.githubusercontent.com/assets/1092707/13671990/241f57be-e6d3-11e5-97ee-a8caf1a168e3.png)

## Summary
It looks that for small number of messages in the input queue the imbalance is pretty big. However is decreases with increasing number of messages.

**Comment by tmasternak** [comment]
@mauroservienti @SzymonPobiega @weralabaj What do you think? We need to make a decision if we are good with the current imbalance in scale-out scenario. I think that from the implementation perspective there are no blockers to postpone that until v3.x.

**Comment by mauroservienti** [comment]
> I think that from the implementation perspective there are no blockers to postpone that until v3.x.

Agree, we can release this later as an improvement.

What is causing the imbalance for low throughput scenarios?

**Comment by tmasternak** [comment]
@mauroservienti The imbalance is caused by the peek-receive mechanism and default concurrency limit. What happens is that each endpoint instance has a single thread doing peeks which query how many messages are there in the input queue. Then it creates a single task for each message but no more than concurrency limit. The peek is done every second and concurrency limit is 100. So with small number of messages (<<100) the chance that the endpoint which peeks the messages first will consume them all is pretty big.

**Comment by tmasternak** [comment]
@MarcinHoppe @mauroservienti I think that it might matter when processing of single message takes considerable amount of time (I mean minutes) and they are written to input queue in batches.In such case we can have throughput which is significantly lower than optimal. However I'm not sure if such load pattern is realistic and in my opinion such things happening are probably sign of design issues. 

That being said I'm not sure if @SzymonPobiega was not dealing with such scenarios implementing adaptive receive algorithm for V2.

**Comment by MarcinHoppe** [comment]
@tmasternak Out of sheer curiosity: could we tune the system in such a case to use lower concurrency limit on a single endpoint and run more competing endpoints?

/cc @mauroservienti @SzymonPobiega

**Comment by tmasternak** [comment]
@MarcinHoppe I think that has a good changes of working. :+1:
