### ISSUE TITLE
Remove the dependency on the DTC when using the multi schema feature

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.SqlServer#157]
Actually in V2 to enable multi-schema the user needs to define multiple connection strings causing the transport to require the DTC. When using multi-schema we should remove this requirement.

Inception: https://github.com/Particular/CustomerSuccess/issues/166

**Comment by ramonsmits** [comment]
Basically, make use of fully qualified table names containing catalog + schema to make use of connection sharing.

**Comment by SzymonPobiega** [comment]
I don't think this is true. When using code API you should be able to specify the schema name and this code: https://github.com/Particular/NServiceBus.SqlServer/blob/master/src%2FNServiceBus.SqlServer%2FSqlServerMessageSender.cs#L36 would get the connection used for receiving the message and use schema-qualified table name.

**Comment by mauroservienti** [comment]
@SzymonPobiega

> I don't think this is true. 

Sorry, what's not true?

**Comment by SzymonPobiega** [comment]
@mauroservienti 

> Actually in V2 to enable multi-schema the user needs to define multiple connection strings causing the transport to require the DTC

I think you can use a single connection string and configure schema in code in V2.

**Comment by mauroservienti** [comment]
@SzymonPobiega 

> I think you can use a single connection string and configure schema in code in V2.

Yes, correct, however it doesn't work in ServiceControl.

**Comment by SzymonPobiega** [comment]
True.

**Comment by mauroservienti** [comment]
[Here is the issue](https://github.com/Particular/ServiceControl/issues/618) related to ServiceControl, we appraciate your input.

**Comment by SzymonPobiega** [comment]
So if I understand V3 correctly (cc @tmasternak ), the address string in V3 contains the schema name so  when we upgrade SC to NSB 6, it should work automatically. It would be hard to fix in NSB 5.

**Comment by tmasternak** [comment]
@SzymonPobiega correct.

**Comment by tmasternak** [comment]
I think that this one is closely related to #156. I think it's worth checking of the effort here. I can create a `spike` issue that will enable us to figure out how much work is needed and decide to do it or not. Thoughts?

**Comment by mauroservienti** [comment]
@tmasternak don't we support the `legacy` mode exactly to address @SzymonPobiega concern about wire compatibility?

**Comment by tmasternak** [comment]
> don't we support the legacy mode exactly to address @SzymonPobiega concern about wire compatibility?

@mauroservienti Do you mean representing addresses with schema on the wire?

**Comment by mauroservienti** [comment]
No, say that we have a multi-schema based environment. Where V6 needs to talk to V5, V6 address is something like destination@schema V5 will use the old approach, even if V6 sends the reply address as sender@schema V5 can use it since the V5 transport will ignore the thing following the @. Correct?

**Comment by tmasternak** [comment]
@mauroservienti  that is correct.

**Comment by tmasternak** [comment]
This is connected to #156. Should I close this one and we can track progress there? /cc: @mauroservienti

**Comment by mauroservienti** [comment]
yeah, replaced by #156
