### ISSUE TITLE
Endpoint name in the connection string is case sensitive

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.SqlServer#159]
When using multi-instance/schema support in V2 and defining connection strings using the format `NServiceBus/Transport/My-Endpoint-Name` the `My-Endpoint-Name` segment is case sensitive, and should not really be.

**Comment by SzymonPobiega** [comment]
The multi-instance support has been removed in V4. I am closing this. @mauroservienti feel free to re-open if you disagree.
