### ISSUE TITLE
Support other RDBMS databases e.g. Oracle

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#166]
There is very little code in the transport that is strictly SQL Server-related. Most of it can be used with other RDBMS databases like Oracle. We should think about either making it a general purpose SQL transport (not SQL Server) or implementing a separate Oracle transport. Here's why:
- We support Oracle persistence through NHibernate
- DTC story with Oracle is far from perfect so using MSMQ and Oracle DB is troublesome
- There are .NET shops, especially in highly regulated domains where IT has long history, where Oracle is a _de facto_ standard for storing any form of data
- We have customers who build their own custom Oracle transports in order to fill that gap

**Comment by seanfarmar** [comment]
From LiveChat today, a customer asking about Oracle transport:

```Hi, we are evaluating NServiceBus for a series of projects in which we can't request the client new servers to host anything besides our WebApp+backend code, and a Db Server, so we can't leverage RabbitMQ for instance
We will have Sql Server in a series of projects, and Oracle in others
I couldn't find an official Oracle transport for NServiceBus, and I've seen there is 
an issue open regarding a generic Sql transport but still no work on it (https://github.com/Particular/NServiceBus.SqlServer/issues/166)
Are you aware of any community/unofficial Oracle transport plugin?
Or, are you aware of any blocking issue in implementing one? 
The Sql Server transport seems to be fairly small and, at a first glance, it doesn't seem to be long to reimplement in Oracle.
We are just worried about transactions and MSDTC really, or issues we can't imagine...
And, just out of curiosity, do you know which is the rationale behind NServiceBus 
having Oracle support for Persistante but not for Transport?! It is quite odd.

This could be a showstopper for us, if we don't find time to implement the transport ourselves or if we do but it will not work (or will be unstable) for whatever reason```

**Comment by SzymonPobiega** [comment]
@seanfarmar should I try to answer them or pass the answer to you?

**Comment by SzymonPobiega** [comment]
@seanfarmar feel free to re-raise this in the PlatDev Incubation area. The SQL transport maintainers are not capable of executing this on their own.
