### ISSUE TITLE
Automate DB creation before running Acceptance and Integration Tests

### ISSUE THREAD

**Issue by weralabaj** [Particular/NServiceBus.SqlServer#170]
In test we have 4 (?) DBs that need to be manually created to run tests. It's irritating because tests fail and I need to investigate.
Solution might be to add db creation to the "reset" script.

Low prio for now.

**Comment by tmasternak** [comment]
I agree it's low prio. We could use `ResetDatabase.sql` script which is running before ATT on build server.
