### ISSUE TITLE
PauseAfterReceiveFailure(Timespan) obsoleted

### ISSUE THREAD

**Issue by weralabaj** [Particular/NServiceBus.SqlServer#171]
As explained here https://github.com/Particular/NServiceBus/issues/3544, in v6 CircuitBreaker's extension method PauseAfterReceiveFailure(Timespan) was obsoleted.

We copied implementation to SQL Server transport without this parameter. The question is should we add it? If not how to explain it?

**Comment by tmasternak** [comment]
@mauroservienti do we have any information about anyone using this setting? /cc: @SzymonPobiega

**Comment by mauroservienti** [comment]
never heard about it.

**Comment by SzymonPobiega** [comment]
Never heard about it.

**Comment by tmasternak** [comment]
Than I propose to not support it in v3. If users complain we can add it in v3.x.
