### ISSUE TITLE
One of Acceptance tests fails randomly

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.SqlServer#173]
This is very likely a problem with acceptance test implementation. A similar problem has been observed for [NServiceBus.NHibernate](https://github.com/Particular/NServiceBus.NHibernate/issues/173). 

Last time it happened:

https://builds.particular.net/viewLog.html?buildId=150459&tab=buildResultsDiv&buildTypeId=NServiceBusSqlServer_2RunAcceptanceTests

and here too

https://builds.particular.net/viewLog.html?buildId=157092&tab=buildResultsDiv&buildTypeId=NServiceBusSqlServer_2RunAcceptanceTests

**Comment by SzymonPobiega** [comment]
I haven't seen this failure for quite some time. Closing this one. @MarcinHoppe feel free to reopen if you disagree.
