### ISSUE TITLE
SQL Server transport version 2.2.2 does not support SQL Server 2008

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus.SqlServer#182]
Taskforce: @MarcinHoppe @tmasternak 

SQL Server transport version 2.2.2 uses [IIF](https://msdn.microsoft.com/en-us/library/hh213574.aspx) logical function in receive and send queries. IIF function is only available in SQL Server 2012 and later, which causes exceptions when endpoint tries to receive messages from the queue in SQL Server 2008.

## Who's affected

Users of SQL Server transport version 2.2.2 that are running SQL Server 2008.

Users of lower versions of the transport are not affected. Users of later versions of SQL Server are not affected.

## Symptoms

The endpoint is unable to send and receive messages from the queue table. When the endpoint tries to receive messages from the queue, it will log the following warnings:

```
An exception occurred when connecting to the configured SQLServer instance
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'IS'.
```

### Plan of Attack
- [x] Convert `IIF` to `CASE`
- [x] [Announcement] (https://github.com/Particular/Announcements/pull/83)

**Comment by MarcinHoppe** [comment]
@Particular/transport-maintainers Do we have a policy around how far back do we support our dependencies, in this case the database?

**Comment by tmasternak** [comment]
@MarcinHoppe I don't think we have any policy. I know that we have been testing SqlServer against Ms Sql 2012 and Ms Sql 2014. That being said I think we should do our best to support 2008 as well. /cc: @mauroservienti

**Comment by MarcinHoppe** [comment]
@tmasternak Do we even run automated tests on SQL Server 2014 now? The TeamCity build configuration has been archived.

Running acceptance tests on all supported versions in the simplest way to ensure we support or at least we know the transport is compatible with all these versions of SQL Server.

**Comment by tmasternak** [comment]
I agree. Part of the scope of fixing this should be setting up the ATT.

**Comment by MarcinHoppe** [comment]
@tmasternak Updated issue description to cover this. Do we need to care about SQL Server 2005? :smile:

**Comment by mikeminutillo** [comment]
Is dropping support for a dependency version considered a breaking change in the context of SemVer?

**Comment by WojcikMike** [comment]
As we agreed that this issue is a bug, can we try to create an action plan. From what I hear:
* Create a hotfix to change the offending queries to work on SQL 2008
* Set up ATT to be run on all supported MS SQL versions

Should we document somewhere versions of MS SQL that we support? readmed.md file + release notes?

**Comment by tmasternak** [comment]
@mikeminutillo http://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api. That said I think the author was referring to software dependencies. 
Not supporting Ms Sql 2008 causes our public Api to break for some users after update and in my opinion should be considered new Major as you mentioned.

**Comment by tmasternak** [comment]
@WojcikMike :+1: for documenting supported versions.

**Comment by MarcinHoppe** [comment]
Should we unlist 2.2.2 from NuGet as it violates SemVer?

**Comment by tmasternak** [comment]
@MarcinHoppe I'd rather release a new patch fixing 2008 support problem.

**Comment by MarcinHoppe** [comment]
:+1:

**Comment by johnsimons** [comment]
So this is a critical issue right ?
