### ISSUE TITLE
Introduce the concept of dialect to support multiple flavors of SQL Server

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.SqlServer#183]
In #182 there was an issue related to unsupported syntax in 2008. A project like NHibernate has the concept of dialects. Here you can make use of 'newer' SQL server version to get more efficient queries.

Maybe it has value to also add this concept to the SQL Transport. Potentially this could make the transport be less coupled to SQL Server opening to the option to support even another RDBMS although that is not the primary intent of this issue.

References:
- https://github.com/nhibernate/nhibernate-core/tree/master/src/NHibernate/Dialect
- http://nhibernate.info/doc/nhibernate-reference/session-configuration.html#configuration-optional-dialects

**Comment by MarcinHoppe** [comment]
In addition to this being a nice refactoring, I like that it opens up a possibility to support other DBMS systems (see #166 for a sample customer request to support Oracle).

**Comment by SzymonPobiega** [comment]
Single the original problem has been fixed and we have not seen any other problems when it comes to compatibility with old versions of SQL Server I propose to close this one. We'll revisit adding dialects if, in future, SQL Server adds a feature that can be leveraged to improve the way the transport works.
