### ISSUE TITLE
Configuration preference order is incorrect. Should be code first then config. 

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus.SqlServer#187]
Based on the recent documentation:

>In Versions 2.1 to 2.x the endpoint-specific connection information is discovered by reading the connection strings from the configuration file with `NServiceBus/Transport/{name of the endpoint in the message mappings}` naming convention. If such a connection string is found, it is used for a given endpoint and this setting has precedence over the code-provided connection information.

However, this is backwards. Code provided configuration should have precedence over what's provided in the app.config. That's currently how the core operates. 
eg. the error q setting will use code config if present https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Recoverability/Faults/ErrorQueueSettings.cs#L14

**Comment by weralabaj** [comment]
@indualagarsamy I've checked using sample and have no idea where that comment comes from. Code has precedence over config as far as I can tell.

**Comment by indualagarsamy** [comment]
@weralabaj - I saw the comment in the linked doco PR. The new doco http://docs.particular.net/nservicebus/sqlserver/configuration accurately reflects your findings. I raised an issue originally because I wasn't sure if the doco was incorrect or if the behavior was incorrect. Closing this issue.
