### ISSUE TITLE
Transport adds missing index when installers are executed 

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.SqlServer#188]
### Problem statement

Queue tables created by versions 2.2.1 (and earlier) of the transport do not create an index on the `Expires` column. When transport version 2.2.2 (or later, including V3) runs on such a queue table, it logs a warning about a missing index and points user at the doco on how to create this index manually.
### Solution proposal

Usually the endpoint will be running using low privilege account that will not have enough rights to create the missing index automatically.

When the user requests that installers are executed, however, it is safe to assume that the running account has enough privileges to create the queue tables, which should be sufficient to create the missing index.
### Scope

The motivation for this is ServiceControl which suffers from warnings in the log after upgrading SQL Server transport to version 2.2.2. The same kind of warnings will be logged when users upgrade from V2 to V3 version of the transport. The issue has to be fixed both on V2 and V3 branches.
### Open questions
- V2: is this a new feature or a bug fix? Can we release this as a hotfix or a minor release?

**Comment by MarcinHoppe** [comment]
@Particular/transport-maintainers @Particular/servicecontrol-maintainers Please chime in on this issue.

**Comment by johnsimons** [comment]
@MarcinHoppe I see this as a bug, hence a hotfix

**Comment by mauroservienti** [comment]
I agree that this is a bug, I don't see this as critical hence the L label. We have a workaround and is not causing any critical failure or data loss. We need to fix it, as a hotfix.

Do we need to do it now?

**Comment by tmasternak** [comment]
As I don't like the fact that SC is putting warnings in he log I this is not a critical one.

**Comment by tmasternak** [comment]
The currently supported version of the transport creates the index on startup.
