### ISSUE TITLE
Public Api Aproval Tests

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#189]
Connects to https://github.com/Particular/PlatformDevelopment/issues/709
Connects to https://github.com/Particular/PlatformDevelopment/issues/732

## Goal
We want to be able to control the types that are exposed as api of `SqlServer`. In order to achieve that we should use ApiComparer in the similar manner that `Core` does.

## Plan Of Attack
- [x] Setup ApiComparer Tests
- [x] Do review of the types currently exposed

Relates to https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/56#issuecomment-200855259

**Comment by SimonCropp** [comment]
should we fix the namespaces and assembly name to match this https://github.com/Particular/PlatformDevelopment/blob/master/designprinciples/nservicebus/namespaces.md  ?

**Comment by tmasternak** [comment]
@SimonCropp Yes. We should do it as part of /Particular/PlatformDevelopment#732. I think that we should:
 * remove `s` from namespaces and assembly name
 * rename projects to mach the conventions

**Comment by danielmarbach** [comment]
Agree this is a good opportunity to do it as part of the major release

**Comment by tmasternak** [comment]
This one is done
