### ISSUE TITLE
Audit message is sent to the address from `NServiceBus.SqlServer.CallbackQueue` header

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#202]
### Symptoms

Audit message is sent to the address from `NServiceBus.SqlServer.CallbackQueue` header.

### Who's affected

All users of version 3 who also have endpoints using version 2.

### Root cause

The legacy callback handling behavior overrides the destination in the routing stage if the *incoming* message is a reply. The intent of the author was probably to override it if the current message being sent is a reply. This stage happens to be executed also for non-user messages like audits and errors. In this case the audit message is redirected to the destination from the legacy callback queue header. Even if the intent was checked on the current message it would not work because it would override the destination of audited or forwarded replies.

### Repro

Run the SQLServer/NHibernate outbox sample with V2 version of `Receiver` and V3 version of `Sender` to notice `Receiver` blowing up with unexpected message (which has been routed to it instead of the audit queue)

### Plan of attack

 * [ ] Evaluate a solution which copies the value from callback queue header to `ReplyTo` header in the message pump
 * [ ] Evaluate a solution which copies the value from callback queue header to `ReplyTo` header in the handling stage (before executing the handlers)
 * [ ] Copy the fix to RabbitMQ transport

**Comment by SzymonPobiega** [comment]
@Particular/transport-maintainers @Particular/tf-v6-launch-plat-dev this needs to go into V6.

**Comment by andreasohlund** [comment]
Is it all v3 users or is it v3 combined with v6?

**Comment by SzymonPobiega** [comment]
@andreasohlund corrected.

**Comment by andreasohlund** [comment]
Flagged as v6 after talking to @tmasternak and  @danielmarbach 

Doesn't seem to be a blocker for beta since it's a combo of callbacks + different versions of the transports. 

@SzymonPobiega since we're not going to do this right away can you make sure that there is enough info in the issue so that we can pick this up later?

Should we raise a plat dev issue or a new issue in rabbit to track that fix?

**Comment by SzymonPobiega** [comment]
@andreasohlund callback receivers are enabled in V2 by default so this thing would blow up whenever you want to reply to a message sent by V2 endpoint. I think it would be worth addressing before we give people V3 and they upgrade some of their endpoints to notice their audit messages are sent elsewhere.

**Comment by andreasohlund** [comment]
Ok, so this would cause issues even if the callbacks are not used. That seems like a beta blocker to me then? cc @Particular/tf-v6-launch-plat-dev

**Comment by danielmarbach** [comment]
But the fix should be simple right? we could just check for the presence of audit headers and the not do it.

**Comment by tmasternak** [comment]
@danielmarbach yes I think that the fix should be relatively simple. 

The approach we considered is to make `ReceiveStrategy` substitute the header. It would allow us to keep the code fully internal to transport seam and would give consistent view to any extension point used by the user i.e. no matter where in pipeline they would tap in form user code perspective the header would always have the same value. 

The downside is that audit and error queues would see different value for the header than the one present in input-queue.

**Comment by SimonCropp** [comment]
possible repro https://github.com/SimonCropp/Bugs/tree/master/SqlVersionInCompat

@SzymonPobiega is looking into it to confirm

**Comment by SzymonPobiega** [comment]
@SimonCropp yes, the repro is OK.

**Comment by SzymonPobiega** [comment]
FYI I've updated the issue description.

**Comment by SimonCropp** [comment]
@SzymonPobiega ok in that case i will attempt to create a test for it and fix tomorrow.
