### ISSUE TITLE
PurgeOnStartup can result in timeout

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.SqlServer#203]
When PurgeOnStartup is set to true a normal `DELETE FROM` is executed:
- https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Queuing/Sql.cs#L7

This can result in a timeout exception when the table contains a large set of records.

Consider using a TRUNCATE statement instead or a bounded DELETE FROM a large set of messages will not result in a timeout exception because all deleted records will be written to the SQL journal.
## Permissions

> The minimum permission required is ALTER on table_name. TRUNCATE TABLE permissions default to the table owner, members of the sysadmin fixed server role, and the db_owner and db_ddladmin fixed database roles, and are not transferable. However, you can incorporate the TRUNCATE TABLE statement within a module, such as a stored procedure, and grant appropriate permissions to the module using the EXECUTE AS clause.

Source: https://technet.microsoft.com/en-us/library/ms177570.aspx

As most endpoints can ALTER as they can also create executing TRUNCATE TABLE should not be an issue.

In case it is, we can always fallback to DELETE FROM.

**Comment by ramonsmits** [comment]
Based the behavior the exception message is strange too:

> 89915 messages was purged from table PerformanceTests_NServiceBus6.x64.exe@[dbo]

Probably should be something like:

> 89,915 messages were purged from table 'PerformanceTests_NServiceBus6.x64.exe@[dbo]'

**Comment by MarcinHoppe** [comment]
Alternatively we could fallback to batched `DELETE TOP`. This would make it easier on the transaction log than an unbounded `DELETE`.

**Comment by mauroservienti** [comment]
The problem I see with `PurgeOnStartup` and why it should be a non supported feature, and it gets more dangerous if implemented with batched deletes, is that it does not take into account in-flight messages:

* the endpoint is off
* the Q contains 100 messages
* the endpoint is configured to `PurgeOnStartup`
* when the endpoint starts up the purge operation starts
* at the same time messages are coming in

In the above scenario `PurgeOnStartup` should operate only on messages that were in the Q before the endpoint start up. Still I don't really see many business scenarios for `PurgeOnStartup`.

**Comment by MarcinHoppe** [comment]
Could this be solved by querying for the oldest `RowVersion` before purging starts and using this in the `WHERE` clause of the `DELETE TOP` statement?

**Comment by mauroservienti** [comment]
Sure, that's an option.

**Comment by MarcinHoppe** [comment]
So it's technically feasible but as I understand it, the question whether we want to support purge on startup if the transport doesn't support it natively remains?

**Comment by tmasternak** [comment]
This behavior is the same in v2 and v3 of `SqlTransport` - both are executing unbounded `DELETE FROM` statement. Do we have any clients complaining about that?

When it comes to permissions (I might be wrong here) I don't think we are recommending running the endpoints with elevated permissions. Those should be only used during endpoint installation, right?

/cc: @ramonsmits

**Comment by mauroservienti** [comment]
> Do we have any clients complaining about that?

I suspect that very few customers utilize this feature other than on dev boxes.

> When it comes to permissions (I might be wrong here) I don't think we are recommending running the endpoints with elevated permissions. Those should be only used during endpoint installation, right?

:+1:

**Comment by SimonCropp** [comment]
i know when i was building NSB apps i was too scared to put PurgeOnStartup anywhere near the production code base. a refactor or someone testing a debug build (in the case of an `Ifdef debug`) and it is message loss.

So i had an explicit unit test that cleared the messages on my dev box. And created an exe tool that we could run on demand in test/integration environments, for the rare case that is was needed.

**Comment by tmasternak** [comment]
I think we have all the context that is needed to tackle this one in the future. I propose to consider this triaged and get back to it for minor release of V6.

Thoughts?

**Comment by ramonsmits** [comment]
Was hit by this again, this time on SQL Azure basis instance. It contained 6,000 messages where purge on startup fails and resulting in the endpoint to not start.

I had to manually delete them via the SQL manager which took 46 seconds.

**Comment by ramonsmits** [comment]
even though truncate requires more permissions it might be an option in a lot of environments. Why not make this purge strategy selectable?

```xml
<add key=“NServiceBus/Transport/SqlServer/PurgeMode” value=“TRUNCATE|DELETE”/>
```

```c#
config.UseTransport<SqlServier>().PurgeMode(PurgeMode.Truncate);
config.PurgeOnStartup(true); // If purge mode is not called, throw an exception stating that selecting a purge mode is explicit.
```

**Comment by tmasternak** [comment]
@ramonsmits the current code is deleting a row in batches. I think this solves this issue. Right?

**Comment by WilliamBZA** [comment]
We propose not making this change but rather releasing a sample showing how one could truncate the table using a feature.

The main reason for not making the change stems from the permissions required for TRUNCATE vs DELETE, and having a flag to differentiate between the 2 adds codepaths that need to be tested and maintained for a low benefit scenario given the small applicability to needing to purge large sets of records (especially since a feature can be used to do this).

Sample [PR](https://github.com/Particular/docs.particular.net/pull/5120).

**Comment by ramonsmits** [comment]
In hindsight after 4 years I would just make it a TRUNCATE statement and not even think about the permissions and not starting if purgeonstartup fails. It is so low prio that it likely isn't worth it although adjusting the query. On the other hand using DELETE FROM results in the data to still be in the SQL logs.
