### ISSUE TITLE
Investigate performance of sending in v2 and v3 in end-to-end scenario

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#225]
## Context
In send only benchmarks **when hosted in console app** we observed ~%40 performance drop in v3 when compared to v2. This has not been observed when running the same benchmarks with NUnit test runner.

We need to make sure we know what is the root cause of such behavior - this might result in different guidelines for user who will be doing self-hosting in NServiceBus v6.

/cc: @SzymonPobiega @danielmarbach

**Comment by MarcinHoppe** [comment]
Resolved by not using VSHost.

**Comment by udidahan** [comment]
Does this mean that the problem was the test and that the performance is equivalent?

**Comment by tmasternak** [comment]
@udidahan this problem was more about consistency of results we were getting for V6 only. It was caused by the way in which the tests were run (inside VSHost).

When it comes to performance comparison between v5 and v6: 
 * In scenarios with high latency between endpoint and infrastructure (e.g. Azure) the V6 is noticeably better than V5. 
 * In other test cases the performance is similar, depending on test scenario V5 or V6 is slightly faster.
