### ISSUE TITLE
Expose the strong type connection construction

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.SqlServer#229]
exposed the creation of the connection as config through passing a delegate to code api.

So this give them full code access to every settings via a strong typed API https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnection_properties(v=vs.110).aspx

**Comment by tmasternak** [comment]
We should make sure that the new api looks as similar to other parts of the code e.g. NHibernate persistence.

**Comment by SzymonPobiega** [comment]
@SimonCropp did you mean a builder-type of API for creating connection without the need to use connection *string*?

**Comment by SimonCropp** [comment]
not really a "builder-type of API". just a func that returns a sqlconnection. they then have full control over it

**Comment by tmasternak** [comment]
@SimonCropp which method from [here](https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/SqlServerTransportSettingsExtensions.cs) did you have in mind? Or is it some other place?

**Comment by SimonCropp** [comment]
@tmasternak damn i did not see that one
