### ISSUE TITLE
Evaluate In-Memory OLTP

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#235]
Let's figure out if we can take advantage of `In-Memory OLTP` feature in `SqlServer` transport. We should probably check if:
 * Transport runs correctly on top of `In-Memory OLTP`
 * We get some performance gains
 * The behavior is the same on `Azure` and `On-premise`

**Comment by MarcinHoppe** [comment]
Duplicate of #265
