### ISSUE TITLE
Evaluate moving `Backwards Compatibility` tests from EndToEnd to `NServiceBus.SqlServer`

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#237]

**Comment by SzymonPobiega** [comment]
While I was going through PoA of https://github.com/Particular/NServiceBus.SqlServer/pull/330 I looked and the current `EndToEnd` tests and realized it would be very painful to add tests for multi-catalog (and missing tests for multi-instance). 

I am thinking about forking the code and moving it to our repo to make it easier to add the most recent (develop) code. The idea would be to reference all the other supported versions via nuget but reference the most recent via project reference. Then test the following:
 * send
 * reply
 * subscribe
 * publish

in various deployment modes:
 * same catalog & schema
 * same catalog, different schema
 * different catalogs, default schema, same instance
 * different catalogs, different schemas, same instance
 * different instances, default schema
 * different instances, different schemas

**Comment by tmasternak** [comment]
Closing this one. The tests were already moved.
