### ISSUE TITLE
Re-design MesagePump

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#238]
Current implementation of `MessagePump` mixes at least two different responsibilities:
- constructing infrastructure for receiving messages
- coordinating message receiving

We should try splitting those two aspects into separate classes.

**Comment by SzymonPobiega** [comment]
@tmasternak we don't really have a process for dealing with refactorings as a separate things right now. Closing this one. If you have strong feelings about this one, please reopen.
