### ISSUE TITLE
Support Serializable transaction isolation level

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#246]
Due to the usage of `READPAST` query hit currently `V3` does not support `Serializable` isolation level.

The outcome of this issue is draft of PoA to fix the bug

**Comment by mauroservienti** [comment]
To be re-evaluated after https://github.com/Particular/NServiceBus.SqlServer/pull/719. https://github.com/Particular/NServiceBus.SqlServer/pull/719 enables support for lease locks, that should remove the need for `READPAST`.

**Comment by mauroservienti** [comment]
Replaced by https://github.com/Particular/NServiceBus.SqlServer/issues/247
