### ISSUE TITLE
Transport supports only Read Committed isolation level

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#247]
Due to the usage of READPAST query hit currently V3 does not support Serializable isolation level.

**Comment by SzymonPobiega** [comment]
What should be the action item here? Throw if user requests `Serializable`?

**Comment by ramonsmits** [comment]
@tmasternak Didn't we have a conversation about isolation levels on the SQL transport some months ago? It was when we fixes the but about connections from the pool having an incorrect isolation level. We then talked about that only READ COMMITTED makes sense and verifying that.

**Comment by tmasternak** [comment]
@ramonsmits correct. With current sql statements I can't see a way for us to support anything above READ COMMITTED.

**Comment by mauroservienti** [comment]
To be re-evaluated after https://github.com/Particular/NServiceBus.SqlServer/pull/719. https://github.com/Particular/NServiceBus.SqlServer/pull/719 enables support for lease locks, that should remove the need for `READPAST`.

**Comment by tmasternak** [comment]
The lease-lock approach is not an option for now due to insufficient performance characteristics.
