### ISSUE TITLE
Make accessing the transport connection easier

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#255]
In V2 we used to have a [helper class](https://github.com/Particular/NServiceBus.SqlServer/blob/master/src/NServiceBus.SqlServer/SqlServerStorageContext.cs) that exposed the connection on the handler level. I think we don't have a similar thing in V3. The user would have to get the `TransportTransaction` from the handler context and then extract the connection from that transaction.

Should we provide a similar API? Note: it would only work for non-DTC modes because in DTC the connection is closed before invoking the pipeline.

**Comment by SzymonPobiega** [comment]
@Particular/sqlserver-transport-maintainers what do you think?

**Comment by SzymonPobiega** [comment]
After discussing this with @MarcinHoppe we agreed this API should be discarded. I'll close the issue when the upgrade guide is updated.

**Comment by SzymonPobiega** [comment]
Doco is already there: http://docs.particular.net/nservicebus/upgrades/sqlserver-2to3 so closing this one.

**Comment by tmasternak** [comment]
@Particular/sqlserver-transport-maintainers I've removed this one from the milestone so it won't get included in Release Notes.
