### ISSUE TITLE
V3 does not throw QueueNotFoundException when destination table queue does not exist

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.SqlServer#256]
### Original V2 behavior ###

When V2 of the transport couldn't insert message row into the destination queue table because the table did not exist, it threw `QueueNotFoundException` which was the handled by the core.

### Current V3 behavior ###

V3 does not detect that row insert failed because the table did not exist and allows for the generic `SqlException` to bubble up to the core, where it is not treated in any special way.

**Comment by SzymonPobiega** [comment]
Resolved in #258
