### ISSUE TITLE
Multi instance connection provider callback

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.SqlServer#264]
### Problem

The callback is called for satellites / subqueues too. This has the result that a satellite queue can use a different connection than the endpoint queue. This even works in V3 as the current version of the multi-instance sample demonstrates but in V2 accessing a satellite queue seem to result in using the connection that is used for the endpoint.

The string value passed to the callback contains the satellite name and the schema. This value cannot really be parsed. Using a **StartsWith** is also not possible as this would not work for overlapping endpoint names

* Satelite queues must be accessed using the same connection as the endpoint queue
* The callback should not be called specifying the subqueue / schema / etc as this prevents from using a value comparison and even if it was called it should not require to parse the string value these values.

Following PR fixes the multi instance sample:

* https://github.com/Particular/docs.particular.net/pull/1607

### Solution
Currently there is no (easy) way to check at the SqlServer transport level if the stringified address that is passed from the Core represents a local endpoints queue or remote destination. 
The problems are caused mainly due to the fact the SqlServer addresses do not have a structure apart from parts before and after `@`. For e.g. `Sales.Something` might be a satellite of logical endpoint named `Sale` or it might be a separate logical endpoint altogether. As a result it is not possible to provide helper methods of type `x.BelongsToEndpoint` and `x.IsQueue`. For the same reason it is  not possible not to call the factory method only for main queue and not satellites or to pass only endpoint name and not full transport address. This is the case in V2 as well where the pull type of configuration methods are called also for satellites.
As a result the decision was made to remove schema part when passing address to the factory and secondly to provide a better sample that would provide more idiomatic approach to returning the connections.

### PoA
- [x] Change extension method and pass only queue name to the factory method
- [x] Provide a better sample for configuring multi-instance

**Comment by tmasternak** [comment]
@Particular/sqlserver-transport-maintainers For v3 we can consider changing [multi-instance connection factory](https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacySqlConnectionFactory.cs#L14) and pass `transportAddress` in a more structured way e.g. tableName + schema. I'm not sure we can make this a lot better though.

**Comment by MarcinHoppe** [comment]
I think this connects to #263. We would probably need to extend this to support multi-catalog in the future?

**Comment by ramonsmits** [comment]
@MarcinHoppe I don't know if it connects. Well, it depends, if you would just consider that the argument only identifies a logical endpoint then it should not included any meta data and if you would look it from the other end then it should contain:

* catalog
* schema
* table
* endpoint
* satellite
* endpoint discriminator
