### ISSUE TITLE
Use `INSTEAD OF` triggers and a shovel process to implement transparent multi-catalog

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#269]
The idea is to use views and `INSTEAD OF` triggers to create surrogate destination tables in all catalogs. These triggers would insert messages to some kind of outgoing queues (one in each database) from where the shovel-like process would take them and move to the destination table. 

The views and triggers would be maintained by the shovel thing automatically. Upon detecting a new queue in one of the databases, it would create corresponding views in all the other databases.

**Comment by MarcinHoppe** [comment]
@SzymonPobiega Are you working on this?

**Comment by SzymonPobiega** [comment]
@MarcinHoppe nope. I am not working on this one right now.

**Comment by tmasternak** [comment]
@SzymonPobiega is this still relevant to spike? Should we close it?

**Comment by SzymonPobiega** [comment]
@tmasternak I spiked it and it proved to be rather impractical. Closing.
