### ISSUE TITLE
Create a AWS lab environment for SQL Server testing

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#270]
* 3 c4.2xlarge instances tagged as `SQL Lab` role: `SQL-1`, `SQL-2` and `SQL-3`
 * SQL Server 2016 Developer edition installed
 * Mixed mode authentication
 * Created a test login `testuser` in each instance. Password same as for the perf test admin account (lastpass)
 * All instances are configured as linked servers, both directions
 * Database `Test` created with table `Queue` with schema identical to SQL transport queue tables

**Comment by SzymonPobiega** [comment]
cc @ramonsmits

**Comment by MarcinHoppe** [comment]
I have not actually read it but this might be relevant:

https://aws.amazon.com/windows/resources/whitepapers/alwayson/

Have you checked if there perhaps is a ready AWS CloudFormation or Azure template we could use?

**Comment by SzymonPobiega** [comment]
@MarcinHoppe nope, using bare AWS for now. I have too little experience with CF (or clouds in general).

**Comment by SzymonPobiega** [comment]
A lab with three machines has been created. Details in the issue description.

**Comment by MarcinHoppe** [comment]
@SzymonPobiega IIUC this has been completed. Can we close?
