### ISSUE TITLE
add code API for controlling QueuePeeker peek interval

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.SqlServer#271]
https://github.com/Particular/NServiceBus.SqlServer/blob/3.0.0-Beta2/src/NServiceBus.SqlServer/Receiving/QueuePeeker.cs#L47

propose supported range: 100ms to 10s

**Comment by HEskandari** [comment]
The suggestion at the backlog grooming session was to:

- Don't allow values less than lower bounds (here 100ms)
- For values larger than the upper bound (here 10 seconds) allow it but also log a warning message.

Do you think that would work @SimonCropp?

**Comment by SimonCropp** [comment]
@HEskandari sounds reasonable to me

**Comment by HEskandari** [comment]
Borht PRs for the code and doco are merged in. This can be closed now.
