### ISSUE TITLE
Id column suffers from fragmentation due to uniqueidentifier usage

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.SqlServer#274]
I know we left the `Id` column as uniqueidentifier around for backwards compatibility reasons. The problem is that this column creates fragmentation especially when used in combination with indexes. For deletes we include `Id` in the index. Which is suboptimal. 

https://blogs.msdn.microsoft.com/sqlserverfaq/2010/05/27/guid-vs-int-debate/

There are multiple things we could do:
- Use sequential GUIDs by using CombGuid generator or `[NEWSEQUENTIALID](https://msdn.microsoft.com/en-us/library/ms189786.aspx)` (compatible with 2008 and higher)
- Exclude Id from Index and delete by RowVersion only (requires index alter, potential risk of deleting wrong message (is it really?)), combine with CombGuid
- Replace Id column with natural bigint identifier (requires index alter, live and on-the-fly migration) but saves 8 bytes per INSERT and SELECT and drastically reduces fragmentation

Thoughts? Any other ideas?

**Comment by SzymonPobiega** [comment]
In the current version of SQL Server transport the [clustered index is based on the RowVersion column](https://github.com/Particular/NServiceBus.SqlServer/blob/master/src/NServiceBus.Transport.SqlServer/Queuing/SqlConstants.cs#L178) which is a sequence so there is no fragmentation.
