### ISSUE TITLE
40 objects of type SqlServerPollingDequeueStrategy

### ISSUE THREAD

**Issue by pawelpabich** [Particular/NServiceBus.SqlServer#28]
Hi,

I'm debugging some problems with transations using windbg and I noticed our worker process has 40 instances of SqlServerPollingDequeueStrategy.  This seems excessive. Should not have we have just one? We have set max concurrency level set to 10. I can provide more data if it's required.

**Comment by SzymonPobiega** [comment]
Fixed by #65
