### ISSUE TITLE
Decide if we want to revert reading messages with expired where statement

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#285]
After talking with @MarcinHoppe  I think that merging of https://github.com/Particular/NServiceBus.SqlServer/pull/233 was premature on my end. There are some consequences that I did not realize. Depending on release schedule for Beta2 we might want to revert the merged changes and proceed with separate issue that will include testing to understand the performance consequences.
Here are the list of questions that we need to answer to understand the implications of the change:
 * Is it fine that the expired message will be deleted only by `ExpiredMessagePurger` that runs every 5 min  and not on message receive?
 * What will happen to processing throughput when many expired messages are in input queue and purger kicks in?
 * What are implications for setup resulting from v2 upgrade when users will not have indexes on `Expired` column?
 * Are we good with not logging any information about expired message removal? - this is what happens when we skip the message on peek
 * What are performance numbers when there is significant number of expired messages arriving to the input queue?

Probably there are some other questions that we might want to ask.

/cc: @MarcinHoppe @danielmarbach

**Comment by tmasternak** [comment]
One additional comment to explain why I think the `delete-on-peek` is safer than the merged solution from @danielmarbach. I think it the case because there is no scenario in which we are executing sql statements that delete more than one row at once.

**Comment by MarcinHoppe** [comment]
@tmasternak Except for the expired messages purger, of course :).

**Comment by danielmarbach** [comment]
Many of these implications already existed before my PR. 

For example

> What will happen to processing throughput when many expired messages are in input queue and purger kicks in?

Problem before

> What are implications for setup resulting from v2 upgrade when users will not have indexes on Expired column?

Problem before because purging depends on it.

> What are performance numbers when there is significant number of expired messages arriving to the input queue?

Problem before since you cannot assume that peeking will always be able to cope with the inserts

The only question of relevance for the merged PR is:

> Is it fine that the expired message will be deleted only by ExpiredMessagePurger that runs every 5 min and not on message receive?

**Comment by tmasternak** [comment]
@danielmarbach I disagree. 

With previous approach scenarios 1, 2 and 3  you quoted were irrelevant/non-existing. When we did deletes with receive the assumption was that, apart from temporary spikes, deletes issued as part of receives would keep up with the pace at which expired messages would arrive. **That would result in `Purger` being effectively idle.**
 
In scenario 2 the question is: "How costly will it be to search for non-expired message when we do not have index on Expired column". Once again issue did not exist previously.

What `peek only non-expired messages` could give us is smaller latency when receiving non-expired messages when we have significant amount on expired messages already in the input queue. 

What tests should answer is if potential problems in scenarios 1-3 do not outweigh assumed benefit.

**Comment by danielmarbach** [comment]
Yeah and I'm saying these assumptions are wrong. Let's discuss ;)

**Comment by tmasternak** [comment]
After discussion with @MarcinHoppe  and @danielmarbach we decided that the current approach (introduced by @danielmarbach) should be kept as is and only when we see problems when doing EndToEnd tests before RC release we might want to revert them. 

The biggest argument for keeping the change is the fact that we optimize for meaningful reads (the message is not expired) and we do not transfer the data from server just to discard it (important in high RTT environments like Azure). We do not have any data/arguments that would indicate performance and/or congestion problems.
