### ISSUE TITLE
Survery multi-instance customers

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.SqlServer#291]
We need to learn what benefits they get (or wish to get) from using multi-instance topology.

**Comment by elovelan** [comment]
Multi-instance + Outbox provides us a way of utilizing geographically diverse endpoints (e.g. we have pub/sub between the US and UK over a WAN) without DTC. Sql Server transport also allows us to leverage competing consumers without utilizing cloud technologies, a distributor or RabbitMQ

Note: we've had to write [custom routing logic](https://docs.particular.net/samples/routing/custom/) and utilize custom endpoint names to make this work and it introduces more coupling between endpoints and instances than we'd like (see **Architecture** point of #180), but we expect that we can improve SoC by leveraging some form of service discovery in the future to map endpoints to queue locations.
