### ISSUE TITLE
Backwards compatiblity test with custom message ID

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.SqlServer#301]
### Scope 
We need to make sure that when V6 endpoint sends a message to to V5 endpoint with custom messageId (which is not a guid) the message id is correctly assigned to message in V5 during processing.

### Outcome
* The message id is correctly passed to V5 when sent from V6. 
* The other way round it's not possible due to know bug #82

**Comment by MarcinHoppe** [comment]
@tmasternak Feel free to add more details here.

**Comment by tmasternak** [comment]
@MarcinHoppe I've checked the behavior and I think we are fine. Feel free to close if you agree.
