### ISSUE TITLE
Shutdown operation should be graceful

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#302]
Currently shutdown logic for V3 is problematic in two aspects:
- It assumes that shutdown should end in 30 sec (this is magic number and not configurable)
- It can cause message loss when endpoint is running in lower transaction levels.

We should change that. When shutdown is requested we should stop spawning new receive tasks but wait until all in-flight messages are processed before completing stop operations.

/cc: @ramonsmits

**Comment by andreasohlund** [comment]
>It can cause message loss when endpoint is running in lower transaction levels.

Only with transactions.none right? (in that case I'd say its ok since tx off means potential message loss no matter what)

We still give the inflight messages 30s to complete right?

Given the above (if correct) is this still a blocker for RC? (given https://github.com/Particular/PlatformDevelopment/pull/957 )

**Comment by ramonsmits** [comment]
@andreasohlund Transaction scope none means message loss for technical reasons like no network connectivity, disk failure, power failure, etc. is expected but you would not expect message loss during a happy path which I think a graceful shutdown is.

It's not only about message loss but also the effort to potentially execute a very compute heavy task again. 

If this is a blocker? It's not critical but can be improved. 

I do know it is a behavioral change as I think core V5 didn't cancel any messages being processed and just waited. If this is the behavior that was agreed by the maintainers than its a matter of fixing the docs and mentioning this in the 5to6 guidance that core V6 transports have the power to kill message processing on their own terms.

**Comment by andreasohlund** [comment]
>expect message loss during a happy path which I think a graceful shutdown is.

Well we give 30s to complete so most shutdowns wouldn't loose messages. So yes if your handlers take more than 30s you might loose a few messages that where inflight on shutdown. But yes we need to talk this through and see what we can do across transports. @Particular/sqlserver-transport-maintainers can you make this call happen? (I want to join if possible)

>If this is a blocker? It's not critical but can be improved.

Agreed, not critical so not blocking the RTM?

**Comment by tmasternak** [comment]
> Transaction scope none means message loss for technical reasons like no network connectivity, disk failure, power failure, etc. is expected but you would not expect message loss during a happy path which I think a graceful shutdown is.

I would not say it's a message loss due to technical reasons. You might have a bug in you code, a GC freeze and probably dozen of other reasons. I do agree however that we could do more in scope of `best-effort`.

> If this is a blocker? It's not critical but can be improved.

I agree I don't think it's blocking RTM.

> yes we need to talk this through and see what we can do across transports. @Particular/sqlserver-transport-maintainers can you make this call happen?

I'll do it on the PlatDev issue

**Comment by tmasternak** [comment]
We don't have any indication that clients experience this scenario in production.
