### ISSUE TITLE
Receive throughput has sawtooth like pattern instead of a more flat/smooth graph

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.SqlServer#303]
While doing a test with different concurrency levels I noticed that most tests had a sawtooth like pattern as is visible in the following image:

![image](https://cloud.githubusercontent.com/assets/152998/18955965/e44a586a-8659-11e6-84e8-14649f679f1e.png)

Maybe the message pump can be made more efficient but it could also be caused due to SQL Server behavior.

**Comment by tmasternak** [comment]
The tests that we conducted in the context of #419 don't show that behavior. That being said this  might be the behavior in some cases but we should dig into it only when this becomes a problematic behavior.

**Comment by ramonsmits** [comment]
@tmasternak This is exactly the behavior I saw locally when testing with the clustered index. That was gone with using the non-clustered index so this has been resolved by the latest release.
