### ISSUE TITLE
Issue warning regarding isolation level settings on the SqlTransport

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#312]
## PoA

- [x] Issue a warning if isolation level is below readcommited https://github.com/Particular/NServiceBus.SqlServer/issues/312
- [x] Update doco https://github.com/Particular/docs.particular.net/pull/3861/commits/3d40b3080a87f4150117671730f7695557a673dc
- [x] Raise an issue to provide a fix in plat dev https://github.com/Particular/PlatformDevelopment/issues/2101

## Context

Right now we enable users to set transaction isolation levels that will be used for receive operations and for send operations (but not in all cases e.g. running with Outbox, Isolated Dispatches, ReceiveOnly and None transactions modes).

I think it does not make sense to run the transport in any other IsolationLevel than ReadCommitted or RepeatableRead. 
- For lower levels + Snapshot we can have message processed twice - we do not have locking on row
- For Serializable - we would have to rewrite queries as we use hints available only there + we would probably not gain anything in terms of processing logic

I propose to change api and enable transaction timeout settings and enforce ReadCommitted for all operations.

See: #310 for isolation level setup details.

/cc: @Particular/sqlserver-transport-maintainers @ramonsmits

**Comment by ramonsmits** [comment]
Yes, limit the transaction isolation level for transport receive operations. It doesn't make sense.
