### ISSUE TITLE
Should we try preventing possible deadlocks caused by native TTBR implementation?

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#313]
## Context

It is possible to have a deadlock between receive operations and expired messages cleanup tasks - see #308  for details. The root cause of the problem is the fact that both operation types need exclusive lock on `RowVersion` and `Expires` indexes, however order in which they acquire those locks depends on execution plan.

Here are question that we should answer:
- Do we need native TTBR support? Maybe discard on receive is enough?
- Do we want to remove Expires index and have lower performance but prevent deadlocks altogether?

/cc: @Particular/sqlserver-transport-maintainers @ramonsmits

**Comment by tmasternak** [comment]
I think we might be able to prevent deadlocks in general. PR comming soon.

**Comment by ramonsmits** [comment]
I would be in favor of supporting TTBR as its a feature that our platform actively uses with SC heartbeats.

**Comment by tmasternak** [comment]
I looks that the recent changes to TTBR logic done in  https://github.com/Particular/NServiceBus.SqlServer/pull/314 minimize the likelihood of the deadlock. 

Closing this one.
