### ISSUE TITLE
Guidelines for migrating from SQL Server transport multi-instance topology to a centralized broker

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.SqlServer#315]
Moved here from PlatDev, because in practice it will be handled by the maintainers. Originally opened as https://github.com/Particular/PlatformDevelopment/issues/947.

We are [advising](http://docs.particular.net/nservicebus/sqlserver/#deployment-considerations) our customers to use SQL Server transport using a single SQL Server instance as a centralized broker.

Customers who are already using multi-instance topology need guidance how to migrate their endpoints and queues from multiple instances to a central broker, preferably without incurring unnecessary downtime.

We can add this to V2->V3 upgrade guide or as a standalone document in the Upgrade Guides section.

**Comment by MarcinHoppe** [comment]
Realistically @tmasternak and myself will not be able to make any progress on it before the holiday break. I will unassign us from this issue for now.

**Comment by SzymonPobiega** [comment]
There is an upgrade guide here https://docs.particular.net/samples/sqltransport/multi-instance-migration/
