### ISSUE TITLE
What maintenance is required for SQL Transport

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus.SqlServer#319]
What is the recommended database maintenance to keep the SQL transport healthy? Does the customer need to regularly update statistics or similar?

**Comment by MarcinHoppe** [comment]
@boblangley We currently don't have any guidance around that other than to do what should typically be done for an OLTP workload.

Is there anything in particular that you think we should cover in docs?

**Comment by boblangley** [comment]
Do we have specific recommendations for what should typically be done for an OLTP workload, or a reference we can direct users to that describes it? Considering the usage of the transport, while OLTP, is there any of these tasks that we can rule out or highlight as being important for ongoing database health?

**Comment by MarcinHoppe** [comment]
Myself and @boblangley agreed that we will explain our general guidance ("talk to your DBA") in the transport doco.

**Comment by SzymonPobiega** [comment]
@tmasternak and myself did extensive long-term tests with SQL Server transport 6.0 which resulted in releasing 6.0.1 patch that drops the clustered index (in favour of a non-clustered one). We have not seen any performance degradation even during long-term high-throughput tests, indicating that there is no maintenance required to keep SQL Server transport running.
