### ISSUE TITLE
Spike a multi-catalog solution

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.SqlServer#325]
The idea for a solution is the following:

1. Catalog will be embedded in the transport address, just like we currently do for the schema,
1. Transport connection string will need to explicitly contain the catalog where the input queue and satellites are stored,
1. If NHibernate persistence is used, it should use the same connection string as the transport (i.e. the same catalog) to avoid escalation to the DTC (if desired),
1. Explicit catalog should be used only for destination queues when sending.

Connects to #149

**Comment by MarcinHoppe** [comment]
@Particular/sqlserver-transport-maintainers I fleshed out the idea for multi-catalog spike. Comments are welcome!

**Comment by SzymonPobiega** [comment]
@MarcinHoppe is we don't use NH persistence, should we allow using a connection string without an explicit catalog and have an API on the transport extensions to set it, just like we can set the schema?

**Comment by MarcinHoppe** [comment]
Seems like a nice addition, we can spike it.

**Comment by SzymonPobiega** [comment]
I've started spiking this but run into a problem with return address. I suspect the same problem will show up when testing subscriptions.

The ReplyTo address in `3.0.x` has `queue@schema` form. When I try using `queue@catalog.schema` it breaks the parsing. It seems like the catalog cannot be added to the address without breaking existing implementations. Possible solutions:
 * Treat this like a bug and release a fix to `3.0` that makes the parsing of address more permissive
 * Send proper reply-to containing catalog in a custom transport header. This has a downside that sometimes the reply-to is overridden and does not point to the current endpoint. It would be nice if the override could contain the catalog name
 
As far as I remember the original intention in `3.0.0` was to make the parsing of address ready for adding a catalog so maybe treating this problem like a bug is the best approach. There is still a possibility of some portion of users staying on 3.0.0 which I don't know what to do with. Failures with `ReplyTo` are quite visible (original message goes to `error`). When a catalog-aware endpoint subscribes, the failure should happen when publishing which should also be quite visible. 

@Particular/sqlserver-transport-maintainers thoughts?

**Comment by tmasternak** [comment]
> The ReplyTo address in 3.0.x has queue@schema form. When I try using queue@catalog.schema it breaks the parsing.

For the sake of discussion: what if we went with `queue@schema@catalog`?

> Release support for multi-catalog when replying or publishing as a patch

What would be the changes included in this patch?

**Comment by SzymonPobiega** [comment]
> For the sake of discussion: what if we went with queue@schema@catalog?

Nice! I didn't think about this. Then the catalog part would be happily ignored by 3.0.0. This means that if both endpoints live in the same catalog, they could talk. Otherwise, the 3.0.0 would have to be configured with legacy multi-instance to reply properly. That's something we need to test in details.

> What would be the changes included in this patch?

Changes in the `QueueAddress` mainly. 

Overall I think I like the "double @" solution best.

**Comment by tmasternak** [comment]
> This means that if both endpoints live in the same catalog, they could talk. Otherwise, the 3.0.0 would have to be configured with legacy multi-instance to reply properly.

I like that :).

**Comment by SzymonPobiega** [comment]
Another question, should we support both forms? I mean, if somebody wants to pass `[catalog].[schema].[table]` as a destination, should that be a supported form that we'll adapt in future in place of the (arguably somewhat awkward) `table@schema@catalog` ?

**Comment by tmasternak** [comment]
> Another question, should we support both forms?

I think that `[catalog].[schema].[table]` is the natural format for anyone dealing with t-sql and it would be great if we could support it. That being said we have at least two problems to solve first:
 * version 2.x expects `x@y` - it takes `x` as table name and ignores the rest
 * version 3.0 expects `x@y` - it take `x` as table name and `y` as schema

In summary I think we won't be able to remove the support for `@`. But I do think we should consider enabling both. 

Maybe for all 3.x it is possible to use the `x@y` only at the wire (protocol level) and at the api level support only `x.y.z`?

**Comment by SzymonPobiega** [comment]
> Maybe for all 3.x it is possible to use the `x@y` only at the wire (protocol level) and at the api level support only `x.y.z`

I like that. Then in 4 we can default to the new form and allow users to enable compatibility mode to use the old form and in 5 remove the `@` form altogether.
