### ISSUE TITLE
Automatically scan database metadata for catalogs and schemas

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#329]
Allow users to enable automatic address discovery based on the endpoint name. Assuming the table name equals endpoint name, we can browse the database metadata to find the catalog and schema for a given destination queue name. 

This would not work if there are multiple tables with the same name in different schemas and/or catalogs but this is an odd scenario. Generally we require each endpoint to have unique name so unless a user overrides the local address of two endpoints, say `EndpointA` and `EndpointB` to be `someQueue`, this auto-discovery should work. 

Worst case, if user enables it and we discover a duplicate entry, we throw telling her/him to disable the autodiscovery or check why she/he has multiple queue tables with the same name.

**Comment by MarcinHoppe** [comment]
I don't think this is an odd scenario. Separate schemas and catalogs holding the same queue tables may occur with DTAP environments and multi-tenant architectures.

**Comment by SzymonPobiega** [comment]
@MarcinHoppe true, but in these cases you never want messages to be routed _between_ the environments. So the auto detection should be limited to a given set of schemas or catalogs. Here are some examples:

### Catalog per environment, schema per endpoint

In this scenario we have a single catalog which holds all queue tables. Each endpoint has its own schema within that catalog. 

```
config.AutodetectQueueLocation(catalogs: new [] {"Queues-Prod"});
```

This implies that queue tables are detected in all schemas in catalog `Queues-Prod`

### Catalog per endpoint, standard schema for queue table

In this scenario each endpoint/service has its own catalog in a single SQL instance. Queue tables have a separate schema e.g. "nsb"

```
config.AutodetectQueueLocations(schemas: new [] {"nsb"}); 
```

This implies that queues are detected in schema `nsb` in all catalogs.

**Comment by mauroservienti** [comment]
@tmasternak @WilliamBZA and I evaluated this and concluded that there is too much magic going on that can lead to strange scenarios. For this reason, we're closing this as withdrawn.
