### ISSUE TITLE
Connection management improvements

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#341]
In V6 we decided that users should explicitly set the max pool size (and we log warning in case there is no explicit value in the connection string) but we didn't give the user any way to actually come up with a reasonable value. Here's a list of random ideas that we can implement to help our users:
 * Provide documentation on how to estimate the number of connections required by NServiceBus in various transaction modes
 * At startup log the estimated number of connections that will be used (using the documented formula)
 * Provide aggregated statistics on connection usage -- every N seconds print the average number of connections in use by the transport (in total and per message)
 * Do not allow concurrent sends from a message handler. At the moment users can create many `Send` task concurrently and `await` them all. If these sends happen to be isolated (or transaction mode is lower than `SendsAtomicWithReceive`) this will result in opening multiple connections simultaneously.

**Comment by weralabaj** [comment]
We'll keep this idea in the backlog, however, seems like a "premature optimization" kind of an issue. As far we haven't received any signals that this is needed from users.

**Comment by SzymonPobiega** [comment]
We can get back to it if we think it is worth it.
