### ISSUE TITLE
Failing message can be processed less times than configured in ImmediateRetries

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#342]
### Description
A message processing failing once can cause failure info being recorded twice for a given message. 

### Scenario
 1. [TryProcessingMessage](https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Receiving/ReceiveWithNativeTransaction.cs#L93) fails. As a result we [store](https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Receiving/ReceiveWithNativeTransaction.cs#L98) failure info.
 2. We try to [rollback](https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Receiving/ReceiveWithNativeTransaction.cs#L42) initial transaction and fail one more time. As a result we record the message failure second time in [catch clause](https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Receiving/ReceiveWithNativeTransaction.cs#L57).

### Impact
In my opinion this is not critical. However when caused by transient connectivity errors it's likely that user handler and `Rollback` operations will fail at the same time. This will lead to less than expected number or retries.
This can happen for all transactional receive modes.

**Comment by MarcinHoppe** [comment]
@Particular/sqlserver-transport-maintainers think that this is an edge case. Closing as won't fix for now.
