### ISSUE TITLE
Store message failure information in sql table

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#344]
### Problem
SqlServer when deployed in competing consumer mode can result retries number begin considerably larger than configured for an endpoint. This is caused by the fact that the message failure cache is stored in-memory per endpoint.

### Potential Solution
How about we store the failure information in a stored sql table.

Spike of possible approach: #343

**Comment by MarcinHoppe** [comment]
I think we discusses this before and dropped the idea because it will not help when there are connectivity problems with the broker.
