### ISSUE TITLE
Schema information is removed from `NServiceBus.ReplyTo` header

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus.SqlServer#345]
### Symptoms

When sending raw messages directly via `ISendMessages`, If the value in the `NServiceBus.ReplyTo` header contains `@` sign, the part of this header after `@` is lost when the message is received.

### Who's affected

Users who send raw transport messages with NServiceBus. Normal usage via `IBus` interface is not affected.

### Details

If the headers collection for an outgoing message contains a schema name it gets stripped out when the message is sent (written to the table). This happens because the call to get the value includes a call to `Address.ToString()` [here](https://github.com/Particular/NServiceBus.SqlServer/blob/2.2.4/src/NServiceBus.SqlServer/TableBasedQueue.cs#L71) and `Address.ToString()` has been configured to [ignore the machine name part of an address](https://github.com/Particular/NServiceBus/blob/support-5.2/src/NServiceBus.Core/Address.cs#L188). This is set up as soon as the [SQL Transport Feature starts up](https://github.com/Particular/NServiceBus.SqlServer/blob/2.2.4/src/NServiceBus.SqlServer/Config/SqlServerTransportFeature.cs#L49).

This is an issue for ServiceControl which is ingesting header data from a V6 endpoint and then retrying it (effectively using V2 of the transport to write it back to the source table). If the original message was sent by an endpoint in a non-default schema then the ReplyToAddress will contain the schema after the `@` symbol. When ServiceControl retries the message using V2 of the transport, this header becomes corrupted. If the Processing Endpoint issues a `Reply()` it will be routed to the wrong address.

NOTE: If the processing endpoint contains custom configuration for the senders input queue then this will actually work.

i.e. `transport.UseSchemaForQueue("Sender", "A");`

If will *not* work if the processing endpoint contains custom configuration for the sending endpoint itself:

i.e. `transport.UseSchemaForEndpoint("Sender", "A");`

I believe this is because the ReplyToAddress is believed to be a physical address and so it doesn't go through Logical->Physical address translation (I could be wrong though).

**Comment by MarcinHoppe** [comment]
Would #156 solve this?

**Comment by mikeminutillo** [comment]
Implementing #156 would necessitate solving this

**Comment by SzymonPobiega** [comment]
https://github.com/Particular/NServiceBus.SqlServer/pull/348 aims to fix this.

**Comment by SzymonPobiega** [comment]
@mikeminutillo please verify if the fix solved the issue.

**Comment by mikeminutillo** [comment]
> @mikeminutillo please verify if the fix solved the issue.

Confirmed
