### ISSUE TITLE
Randomly delayed delivery for testing

### ISSUE THREAD

**Issue by Tobias-Gr** [Particular/NServiceBus.SqlServer#347]
Hi,
for testing we would like to be able to delay messages randomly in order to simulate infrastructure problems and get aware of false assumptions in our code regarding the sequence of messages (kind of a chaos monkey on messaging level). Do you have any hints how to achieve this on transport level for SqlServer transport?

Thanks!

**Comment by MarcinHoppe** [comment]
@Tobias-Gr Thanks for asking. I think the easiest way to do it is to create a custom behavior at the incoming physical message stage. Such a behavior could introduce random delays before the rest of the incoming pipeline is invoke or even throw exceptions to simulate errors. Endpoint concurrency and artificial delays for randomly selected messages should be effective simulation for out of order message arrival.

The same technique can be used to simulate delays and failures on the send side.

Please take a look at the following documentation pages:
- [Steps, Stages and Connectors](https://docs.particular.net/nservicebus/pipeline/steps-stages-connectors)
- [Manipulate Pipeline with Behaviors](https://docs.particular.net/nservicebus/pipeline/manipulate-with-behaviors)

One thing to keep in mind is correlation of these randomly injected failures with other events in the system. Logging what has been injected for each message ID looks like a good start.

Does this help?

**Comment by Tobias-Gr** [comment]
Sounds good! Thank you!

**Comment by MarcinHoppe** [comment]
Cool. I'll close this issue then. 

If you have any further questions, you can also reach out to us at support@particular.net or via the Google Groups.
