### ISSUE TITLE
Stopping transport from custom Fault Manager causes app to deadlock

### ISSUE THREAD

**Issue by pawelpabich** [Particular/NServiceBus.SqlServer#35]
Hi,

Let me first provide some context. What we are trying to do is:
* to process only one message at a time thus max concurrency is set to 1 and we have no retries
* when a message handler throws exception we want to stop processing all other messages as the order of processing matters
* we don't want to move the problematic message to the error queue, we simply want to stop the transport and then resume it once the problem is fixed

Stopping  is done by calling Bus.Transport.ChangeMaximumConcurrencyLevel(0)  from CustomFaultManager.ProcessingAlwaysFailsForMessage. The resume code calls Bus.Transport.ChangeMaximumConcurrencyLevel(1). This causes the app to deadlock with the latest version of the transport 1.2.2. It *works*  with 1.2.1. The problem seems to be the CountDownEvent introduced in 1.2.2. Basically the message processing and fault handler are called on the same thread to the worker thread has no chance to call Singnal before we call Wait in the Stop method.  I attached the full stacktrace so you can get more details. 

Now the question is, are we doing something completely wrong here? If so, how would you solve this problem?

Thanks

Pawel

![image](https://cloud.githubusercontent.com/assets/347637/2896670/c47fff68-d570-11e3-9539-8ab11d1ad21e.png)

**Comment by SzymonPobiega** [comment]
@pawelpabich we're in process of designing an in-order message processing feature. Here comes a question: are your messages in any way labeled by the legacy application so that we can detect that a message is missing and wait for it or are you purely relying on order messages were put into the queue and that order must be preserved?

**Comment by pawelpabich** [comment]
Hi,

Order of messages in the queue is the source of truth here.

**Comment by tmasternak** [comment]
@pawelpabich do you any more help on that?

**Comment by pawelpabich** [comment]
We still use Task.Run as a workaround. Are you planning any work in this area ?

**Comment by tmasternak** [comment]
@pawelpabich I'm not aware on any changes that we are planning for V5 but let me verify that.

**Comment by tmasternak** [comment]
@pawelpabich Currently there are no plans to do work in this area in V5. I'm closing this issue.
