### ISSUE TITLE
Clarify when to use UseSchemaForEndpoint vs UseSchemaForQueue

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.SqlServer#350]
Looking at this doco section:

https://docs.particular.net/nservicebus/sqlserver/connection-settings#custom-schema-per-destination

it is not clear when `UseSchemaForEndpoint` must be used versus `UseSchemaForQueue`.

Add clarification to the doco and consider creating a multi-schema sample.

**Comment by SzymonPobiega** [comment]
@MarcinHoppe would this be enough: https://docs.particular.net/nservicebus/sqlserver/addressing#resolution-schema

**Comment by MarcinHoppe** [comment]
Not sure I, as a customer, would know which one to choose based on this description.

A sample might be a better idea to illustrate the differences.

**Comment by MarcinHoppe** [comment]
Resolved by Particular/docs.particular.net#2725.
