### ISSUE TITLE
Right square brackets (`]`) are not supported inside queue name

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#355]
### Symptoms

Endpoint using installers cannot create its receiving queue if it contains right square brackets `]`.

### Who's affected

Users who use installers to set up the queues

### Root cause

The queue creator does not use proper escaping mechanism.

**Comment by SzymonPobiega** [comment]
If we fix it, another anomaly that shows up wrong queue name is endpoint name has brackets around it e.g. `[MyEndpoint]`.

**Comment by MarcinHoppe** [comment]
This has been done. Closing.
