### ISSUE TITLE
Align table naming with SQL persistence

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#361]
SQL persistence uses `_` to separate parts in a table name while SQL transport uses `.`. Add an opt-in option to use `_`.

**Comment by SimonCropp** [comment]
isnt this https://docs.particular.net/nservicebus/sql-persistence/saga#table-structure-table-name sufficient ?

**Comment by SimonCropp** [comment]
wrong url https://docs.particular.net/nservicebus/sql-persistence/#installation-table-prefix

**Comment by SzymonPobiega** [comment]
@SimonCropp this is about changing the SQL transport to allow similar customization as SQL persistence allows with the option you mentioned. @markgould  pointed out dots might not be as easy to work with from maintenance point of view.

**Comment by SimonCropp** [comment]
@SzymonPobiega yeah sorry already deleted comments

**Comment by SzymonPobiega** [comment]
This would be a breaking change. Not likely to happen in near future.
