### ISSUE TITLE
Update to Core version 6.3.0

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#363]
## Scope
Update ATT to the newest 6.3.0.

**Comment by MarcinHoppe** [comment]
Is this about updating acceptance tests or reference to the Core?

**Comment by tmasternak** [comment]
Both. Added proper description

**Comment by MarcinHoppe** [comment]
Why do we need to upgrade reference to the Core?

**Comment by tmasternak** [comment]
Looking at the features I would say default error queue is something clients can benefit.

**Comment by MarcinHoppe** [comment]
But how does that require a change in the transport? Isn't this a Core-only feature.

**Comment by tmasternak** [comment]
@MarcinHoppe you are right I got confused.

**Comment by SzymonPobiega** [comment]
We're at 7 so we can close it, right?
