### ISSUE TITLE
Migrate to Visual Studio 2017

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#365]
## Scope
Migrate .sln and .csproj files to VS 2017 structure

**Comment by SimonCropp** [comment]
FYI u will need to update fody when u do this

**Comment by SimonCropp** [comment]
@tmasternak done this for 50+ projects now. happy to do it for the sql sln, or help out if u need

**Comment by tmasternak** [comment]
@SimonCropp thx a lot! Would it work if I could have an initial stab at it and consult any problems, ask for review? I would really like to get that knowledge?

**Comment by SimonCropp** [comment]
No worries. Ping me if u hit any walls

**Comment by SimonCropp** [comment]
@tmasternak want me to take this over?

**Comment by SzymonPobiega** [comment]
@SimonCropp we want to first merge the 3.1 PRs. Let's pause the csproj migration till its done.

**Comment by SzymonPobiega** [comment]
Done via #375
