### ISSUE TITLE
Decide how we want to tackle the "multi-instance" problem

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#366]
The multi-instance is deemed to be removed in 4.0. This blocks the major release until the multi-instance is solved. The native timeouts TF would like to release the native timeout support as a major release so I think we should try to unblock them.

Here's what I think how multi-instance can be replaced:
 * Most of the usages can be migrated to multi-catalog feature that has been scheduled for 3.1 (not yet released)
 * The cases where there actually are multiple instances, not catalogs, can be addressed via a bridge https://github.com/SzymonPobiega/NServiceBus.Bridge and SC adapter (per instance)

@Particular/sqlserver-transport-maintainers what do you think?

**Comment by SzymonPobiega** [comment]
The legacy multi-instance has been removed. Do we need to do anything else here @Particular/sqlserver-transport-maintainers ?

**Comment by MarcinHoppe** [comment]
I think doco deserves an update after the multi-catalog feature has been released. Especially this page here: https://docs.particular.net/transports/sql/deployment-options.

**Comment by SzymonPobiega** [comment]
Here's the doco PR https://github.com/Particular/docs.particular.net/pull/3550. Closing.
