### ISSUE TITLE
Native implementation of publish/subscribe pattern

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#373]
Implement support for publish/subscribe within the transport itself so that it does not have to depend on the message-driven publish/subscribe provided by the core.

The implementation is based on the fact that all endpoints that use SQL Server transport connect to the same instance of SQL Server and therefor can share a single table that contains the mapping of event types to subscribed endpoints.

<details>
Implement the pub/sub in the SQL Server transport by using a subscriber table internally (not depending on the persistence)

 * Allow connectivity with legacy subscribers by processing the subscribe messages in the transport and updating the subscription table
 * Allow connectivity with legacy publishers by exposing API for sending subscribe messages e.g. in the subscription manager check if Publishers table contains entry for a given event type and if so, then use legacy mode
 * Expose API for configuring the subscription table's catalog & schema
 * Allow using multiple subscription tables -- configured per endpoint -- not sure about that
<details>

**Comment by markgould** [comment]
I think this would be a great addition. It has always seemed a little strange having the subscriptions be a part of the persistence layer rather than at the transport layer.

**Comment by SzymonPobiega** [comment]
Implemented in https://github.com/Particular/NServiceBus.SqlServer/pull/527
