### ISSUE TITLE
Why does this package depend on GitVersionTask?

### ISSUE THREAD

**Issue by larsw** [Particular/NServiceBus.SqlServer#398]
Why does this package depend on GitVersionTask? I can understand if this is a development dependency, but it seems wrong that it is a production dependency.

**Comment by MarcinHoppe** [comment]
@larsw We've just noticed it and are fixing this right now. Expect a new beta package today.

**Comment by larsw** [comment]
![success](https://user-images.githubusercontent.com/63235/30201097-c6a3b840-9479-11e7-96c0-12a4010700b0.jpg)

My work here is done.

**Comment by MarcinHoppe** [comment]
@larsw Many thanks for watching the dependencies like a hawk!
