### ISSUE TITLE
v4 beta 3 of SqlTransport is  inflicting GitVersionTask on me whether I want it or not

### ISSUE THREAD

**Issue by gbiellem** [Particular/NServiceBus.SqlServer#401]
The  [package reference](https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/NServiceBus.SqlServer.csproj#L32) in the csproj does not have PrivateAssets="All" against it so it is being installed as a dependency.   

This is messing with the build number of our projects since don't use GitVersion

**Comment by MarcinHoppe** [comment]
Thanks @gbiellem! It looks like `develop` is tad behind but this has been addressed on the release branch already:

https://github.com/Particular/NServiceBus.SqlServer/commit/2c738bd06cbd6cbf4bf0a022e5d955521186b765#diff-25d902c24283ab8cfbac54dfa101ad31

**Comment by gbiellem** [comment]
Hi @MarcinHoppe  - Glad you are on top of it.  ETA on this reaching nuget?

**Comment by gbiellem** [comment]
For  now we have added the following to the affected csproj files to effectively disable GitVersionTask, so it's not stopping us using the beta, but is pretty annoying

```
<!-- Temp Hack to disable GitVersionTask (NSB SQL Transport beta 3 is the culprit  -->
  <PropertyGroup>
    <UpdateAssemblyInfo>false</UpdateAssemblyInfo>
    <WriteVersionInfoToBuildLog>false</WriteVersionInfoToBuildLog>
    <GetVersion>false</GetVersion>
  </PropertyGroup>

```

**Comment by MarcinHoppe** [comment]
We plan to have beta 4 on MyGet before the end of the week.

/cc @SzymonPobiega

**Comment by SzymonPobiega** [comment]
@gbiellem Beta4 is on myget

**Comment by MarcinHoppe** [comment]
@gbiellem Can you confirm that beta4 does not drag GitVersion as a dependency anymore?

**Comment by gbiellem** [comment]
@MarcinHoppe @SzymonPobiega  Thanks! That's fixed it.  :)

**Comment by MarcinHoppe** [comment]
@gbiellem Great to hear that! Closing.
