### ISSUE TITLE
Beta of SQL Transport - installers create queues in debug regardless

### ISSUE THREAD

**Issue by gbiellem** [Particular/NServiceBus.SqlServer#403]
According to the V6 to V7 upgrade guide installers are only executed if `EnableInstallers` is called.
This is the case for SQL Persistence beta but not the SQL Transport Beta.  It's still doing the V6 behavior of creating queues on F5 in debug.  Aside from inconsistent it would be a little confusing to an end user as to why only some tables were present

**Comment by MarcinHoppe** [comment]
Thanks for reporting this @gbiellem. I am observing the same behaviour on samples even without the debugger attached.

Which version of the Core are you using? Can I assume the most recent beta of the transport?

**Comment by gbiellem** [comment]
@MarcinHoppe  Latest of everything.... From the csproj..
```
<PackageReference Include="NServiceBus" Version="7.0.0-beta0007" />
<PackageReference Include="NServiceBus.Autofac" Version="7.0.0-beta0002" />
<PackageReference Include="NServiceBus.Persistence.Sql" Version="3.0.0-beta0003" />
<PackageReference Include="NServiceBus.Persistence.Sql.MsBuild" Version="3.0.0-beta0003" />
<PackageReference Include="NServiceBus.Serilog" Version="4.0.0-beta001" />
<PackageReference Include="NServiceBus.SqlServer" Version="4.0.0-beta0004" />
```

**Comment by MarcinHoppe** [comment]
Thanks. Looking into this now.

**Comment by MarcinHoppe** [comment]
@gbiellem This turned out to be a bug in the core. I am closing this one in favor of Particular/NServiceBus#5023.
