### ISSUE TITLE
Add startup diagnostics info

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.SqlServer#404]
We can now capture [startup diagnostic information](https://docs.particular.net/nservicebus/hosting/?version=core_7#startup-diagnostics).

We need to decide what info is worth logging and implement it.

Connects to https://github.com/Particular/DotNetCoreLaunch/issues/78

## PoA

- [x] ~~Configured transactionality level (i.e. TransactionScope, SendsAtomicWithReceive, etc.)~~
   - Seems like this should be logged by Core https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/Transport/Config/TransportExtensions.cs#L150
- [x] Native delayed-delivery (yes/no) + settings (batch size, interval, etc.)
   - [x] Timeout manager (enabled/disabled)
- [x] Circuit breaker settings
- [x] TTBR purge at startup (enabled/disabled)

**Comment by ramonsmits** [comment]
Please execute `SELECT @@VERSION` on SQL Server to capture SQL Server version info. This helps us to understand if the customer is running with the latest patches on their SQL box.

**Comment by weralabaj** [comment]
I propose to capture:
- Configured transactionality level (i.e. TransactionScope, SendsAtomicWithReceive, etc.)
- Native delayed-delivery (yes/no) + settings (batch size, interval, etc.)
- Timeout manager (enabled/disabled)
- Custom schema
- Multiple connection strings
- Circuit breaker settings
- TTBR purge at startup (enabled/disabled)

**Comment by weralabaj** [comment]
@Particular/sqlserver-transport-maintainers Anything missing that should be included ☝️

**Comment by SzymonPobiega** [comment]
Multiple connection strings are no longer supported but multiple schemas/catalogs should be reported. Question is how detailed should the report be i.e. if we should report yet/no or the actual configuration. The latter is accessible through https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Addressing/EndpointSchemaAndCatalogSettings.cs and https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Addressing/TableSchemaAndCatalogSettings.cs

**Comment by weralabaj** [comment]
@SzymonPobiega @tmasternak We didn't document that diagnostic info output for sql persistence, I'm not sure if we should do that for sql server/both?
I think it'd be more sensible to extract this part https://docs.particular.net/nservicebus/hosting/#startup-diagnostics and only remark that downstreams can add their own diagnostic data, but it may change over time.
Thoughts?

**Comment by weralabaj** [comment]
https://github.com/Particular/docs.particular.net/pull/3862
