### ISSUE TITLE
Document PurgeExpiredMessagesOnStartup

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.SqlServer#407]
We need to document that we have this new API, what parameters it takes and what happens then users turn it on.

**Comment by SzymonPobiega** [comment]
I am on it

**Comment by MarcinHoppe** [comment]
👍

**Comment by SzymonPobiega** [comment]
Doco PR created https://github.com/Particular/docs.particular.net/pull/3366
