### ISSUE TITLE
Connectivity problems cause excessive logging

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.SqlServer#411]
### Reproduction

1. Configure the endpoint with high concurrency (e.g. 50) and high pool size (e.g. 80).
1. Start the endpoint.
1. Stop the SQL Server instance.

### Expected outcome

The transport does not log every connection attempt at the Warn level. Changes of the overall connectivity status should be reported.

### Actual outcome

Every connection attempt is logged. This floods the log and makes it unreadable after very short time.

**Comment by MarcinHoppe** [comment]
I am not working on at the moment so I remove my assignment for now.

**Comment by SzymonPobiega** [comment]
Fixed in https://github.com/Particular/NServiceBus.SqlServer/releases/tag/4.1.0
