### ISSUE TITLE
Clustered index on RowVersion column causes contention

### ISSUE THREAD

**Issue by kbaley** [Particular/NServiceBus.SqlServer#419]
Based on case 33371. SQL Transport 2.2.1 on NSB 5.2.12.

In one customer's environment, the [SQL that deletes a message](https://github.com/Particular/NServiceBus.SqlServer/blob/support-2.2/src/NServiceBus.SqlServer/TableBasedQueue.cs#L256-L259) when it is received caused a lot of contention to the point where the CPU spiked and the endpoint had to be restarted and the indexes re-created. This would solve the problem temporarily but it would come back a short time later.

Switching the [RowVersion column index](https://docs.particular.net/transports/sql/runtime-sql) from clustered to non-clustered brought the contention down to manageable levels.

**Comment by SzymonPobiega** [comment]
@kbaley sounds reasonable to me.

**Comment by tmasternak** [comment]
I think that testing will be crucial here.

**Comment by SzymonPobiega** [comment]
Fixed in 6.0.1
