### ISSUE TITLE
Issue with .Net Core on Linux

### ISSUE THREAD

**Issue by markgould** [Particular/NServiceBus.SqlServer#429]
Working on moving an endpoint to .Net Core 2. Endpoint starts up successfully from VS/dotnet run, but when running inside a Docker container (Linux) I get the following error:

If anyone else encounters this error:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.ProviderBase.DbConnectionPool.DeactivateObject(DbConnectionInternal obj)
   at System.Data.ProviderBase.DbConnectionPool.PutObject(DbConnectionInternal obj, Object owningObject)
   at System.Data.ProviderBase.DbConnectionInternal.CloseConnection(DbConnection owningObject, DbConnectionFactory connectionFactory)
   at System.Data.SqlClient.SqlConnection.Close()
   at NServiceBus.Transport.SQLServer.SqlServerTransportInfrastructure.<CheckForAmbientTransactionEnlistmentSupport>d__13.MoveNext()
```
It's related to this issue: https://github.com/dotnet/corefx/issues/26965

The workaround right now is to reference the latest System.Data.SqlClient from myget: https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Data.SqlClient

**Comment by bording** [comment]
> Working on moving an endpoint to .Net Core 2. Endpoint starts up successfully from VS/dotnet run

@markgould when running from `dotnet run`, was that on Windows or Linux? I've just tried running an endpoint on Linux (not inside a container) and I'm not seeing the exception. If you are seeing the exception outside of a container, having a project that reproduces the problem would be helpful.

The `CheckForAmbientTransactionEnlistmentSupport` code in the stack trace was added in #428 to prevent using TransactionScopes with versions of System.Data.SqlClient that don't support them (anything before 4.5.0).

**Comment by markgould** [comment]
I ran it from windows with dotnet run and it worked fine. What version of System.Data.SqlClient are you using? I was having the issue with 4.5.0-preview1-26216-02. I don't have a Linux VM at the moment but I could spin one up and try with that version.

**Comment by bording** [comment]
@markgould I was using the latest non-preview release, 4.4.2. That's the version the 4.0.0-rc0003 transport package is built against, and the one that it will pull in by default via transitive reference.

I recommend using that one until 4.5.0 is actually released. Can you try that and let me know if you have a problem with your container?

**Comment by markgould** [comment]
Ah, ok I see what happened. I used 4.4.2 at first and got the message you mentioned "System.Exception: 'Pre start-up check failed: The version of System.Data.SqlClient in use does not support enlisting SQL connections in ambient transactions, so the TransactionScope transport transaction mode cannot be used. Use `EndpointConfiguration.UseTransport<SqlServerTransport>().Transactions` to select a different transport transaction mode.'" 
So I then upgraded to the latest pre-release and got the other exception.

**Comment by bording** [comment]
Once .NET Core 2.1 is released, that will be when System.Data.SqlClient 4.5.0 should be final as well.

That version of the client will support enlisting in ambient transactions, so you shouldn't need to use a different transport transaction mode. 

FYI, even with ambient transactions enlistment, .NET Core 2.1 still won't support MS DTC.

**Comment by markgould** [comment]
Awesome, thanks. Yeah, I noticed that with MS DTC. Is the guidance going to be to just use the outbox pattern with .NET Core?

**Comment by bording** [comment]
Yes, you should be able to use the Outbox feature with .NET Core. Where possible, you can also try and make your handlers idempotent and able to accommodate duplicates.

**Comment by markgould** [comment]
To try and pinpoint the issue I've logged the Saga Id, so you can see the same saga instance completes and then receives further messages. I've bolded the completion lines and removed the stack traces.

> 2018-03-02 21:40:46.196 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Received StartOrder message 6995c33a-3bfc-440c-9de1-d23fb6fe5a60. Starting Saga
> 2018-03-02 21:40:46.202 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order will complete in 3 seconds
> 2018-03-02 21:40:47.111 INFO  ShipOrderHandler Order Shipped. OrderId 6995c33a-3bfc-440c-9de1-d23fb6fe5a60
> 2018-03-02 21:40:47.172 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:47.173 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:47.172 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:47.195 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:47.181 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:47.188 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:48.120 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:48.121 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:48.155 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:48.128 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '9cc452de-0d68-40f0-9dc2-a898003ca307' because of an exception:
> System.Exception: Optimistic concurrency violation when trying to save saga OrderSaga e1203148-024a-4ac1-8434-a898003ca2e2. Expected version 1.  
> 2018-03-02 21:40:48.128 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '1e3386ef-62a3-4446-baf2-a898003ca357' because of an exception:
> System.Exception: Optimistic concurrency violation when trying to save saga OrderSaga e1203148-024a-4ac1-8434-a898003ca2e2. Expected version 1.  
> 2018-03-02 21:40:48.191 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:48.182 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:48.207 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:48.148 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:48.199 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:49.133 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '8a88e746-d7ad-4a08-bce3-a898003ca462' because of an exception:
> System.Exception: Optimistic concurrency violation when trying to save saga OrderSaga e1203148-024a-4ac1-8434-a898003ca2e2. Expected version 2.  
> 2018-03-02 21:40:49.136 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:49.176 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:49.182 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:49.213 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:49.137 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:49.135 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '1e3386ef-62a3-4446-baf2-a898003ca357' because of an exception:
> System.Exception: Optimistic concurrency violation when trying to save saga OrderSaga e1203148-024a-4ac1-8434-a898003ca2e2. Expected version 3.  
> 2018-03-02 21:40:49.136 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:49.308 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:49.136 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:49.556 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:49.486 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:49.520 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:49.662 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:50.297 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '65eb16d2-5756-4ab5-9483-a898003ca5ba' because of an exception:
> System.Exception: Optimistic concurrency violation when trying to save saga OrderSaga e1203148-024a-4ac1-8434-a898003ca2e2. Expected version 4.  
> 2018-03-02 21:40:50.297 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '84b5f966-88f8-486b-9ee4-a898003ca5c4' because of an exception:
> System.Exception: Optimistic concurrency violation when trying to save saga OrderSaga e1203148-024a-4ac1-8434-a898003ca2e2. Expected version 4.  
> 2018-03-02 21:40:50.298 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '8a88e746-d7ad-4a08-bce3-a898003ca462' because of an exception:
> System.Exception: Optimistic concurrency violation when trying to save saga OrderSaga e1203148-024a-4ac1-8434-a898003ca2e2. Expected version 4.  
> 2018-03-02 21:40:50.332 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:50.340 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:50.299 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:50.357 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:50.299 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '85867864-4f47-49eb-b612-a898003ca538' because of an exception:
> System.Exception: Optimistic concurrency violation when trying to save saga OrderSaga e1203148-024a-4ac1-8434-a898003ca2e2. Expected version 4.  
> 2018-03-02 21:40:50.322 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:50.310 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:50.599 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:50.538 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:50.507 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:50.780 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:51.309 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '65eb16d2-5756-4ab5-9483-a898003ca5ba' because of an exception:
> System.Exception: Optimistic concurrency violation when trying to save saga OrderSaga e1203148-024a-4ac1-8434-a898003ca2e2. Expected version 6.  
> **2018-03-02 21:40:51.320 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 with OrderId 6995c33a-3bfc-440c-9de1-d23fb6fe5a60 completed**
> 2018-03-02 21:40:51.344 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:51.357 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:51.311 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '84b5f966-88f8-486b-9ee4-a898003ca5c4' because of an exception:
> System.Exception: Optimistic concurrency violation when trying to save saga OrderSaga e1203148-024a-4ac1-8434-a898003ca2e2. Expected version 6.  
> 2018-03-02 21:40:51.311 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '2634f5aa-8c01-4e3f-b2a3-a898003ca68e' because of an exception:
> System.Exception: Optimistic concurrency violation when trying to save saga OrderSaga e1203148-024a-4ac1-8434-a898003ca2e2. Expected version 6.  
> 2018-03-02 21:40:51.378 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:51.400 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:51.414 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:51.406 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
> 2018-03-02 21:40:52.320 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '84b5f966-88f8-486b-9ee4-a898003ca5c4' because of an exception:
> System.Exception: Optimistic concurrency violation when trying to save saga OrderSaga e1203148-024a-4ac1-8434-a898003ca2e2. Expected version 9. 
> 2018-03-02 21:40:52.332 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Order changed.
> 2018-03-02 21:40:52.338 INFO  OrderSaga Saga Id e1203148-024a-4ac1-8434-a898003ca2e2 Timeout already requested
>
