### ISSUE TITLE
Support for "SQL Server AlwaysOn"

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.SqlServer#43]
Is SQL Server AlwaysOn supported by the SQL Transport?

**Comment by andreasohlund** [comment]
Just for completeness, always on got dtc support in tje 2016 version https://blogs.technet.microsoft.com/dataplatform/2016/01/25/sql-server-2016-dtc-support-in-availability-groups/ I know of a Swedish customer that is using it

**Comment by mauroservienti** [comment]
A British one as well is using it.
