### ISSUE TITLE
Should Expires  column be a datetime2(0)?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.SqlServer#437]
`[datetime2](0)`

http://www.sqltact.com/2012/12/on-advantages-of-datetime2n-over.html

https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-2017

> Use the time, date, datetime2 and datetimeoffset data types for new work. These types align with the SQL Standard. They are more portable. time, datetime2 and datetimeoffset provide more seconds precision. datetimeoffset provides time zone support for globally deployed applications.

**Comment by weralabaj** [comment]
So the main component of this task would be to verify the wire compatibility?

**Comment by SzymonPobiega** [comment]
@weralabaj yeah. Send from the new version of code to old version of table and vice versa.

**Comment by SimonCropp** [comment]
would an installer convert the data type on existing tables?

**Comment by SzymonPobiega** [comment]
@SimonCropp not sure about that. I can smell too much magic in such a solution.

**Comment by SimonCropp** [comment]
I am ok with that. So what would the migration story be?

**Comment by SzymonPobiega** [comment]
@SimonCropp I guess that a warning with a doco link pointing to a script that can convert the column would be the safe way to do it. The reason why I am afraid of automatic migration in the installer is the behavior if the table queue table contains huge number of records.

**Comment by SimonCropp** [comment]
Seem the answer is yes. So i will close this
