### ISSUE TITLE
Ignore catalog in subscription

### ISSUE THREAD

**Issue by markgould** [Particular/NServiceBus.SqlServer#438]
Versions:
NServiceBus.SqlServer 4.0.0-rc0003
NServiceBus.Persistence.Sql 4.1.0-beta0001

Is there a way to ignore the catalog name used in the subscription and instead use the catalog specified in the transport connection string?

We have two environments, Test and Prod (running on the same SQL instance) it looks something like this
Foo
NSB
FooTest
NSBTest

When database Foo gets refreshed into test, we are seeing messages from test get sent to production, due to the way the subscriptions are happening. The Subscriber in the Endpoint_SubscriptionData table has a value of "EndpointName@[dbo]@[NSB]" and "EndpointName@[dbo]@[NSBTest]"

Is there a way to have it use only the table name and schema in the subscription and not include the catalog name?

**Comment by SzymonPobiega** [comment]
@markgould the idea of including catalogs was to be able to send/publish messages between catalogs if they are hosted on the same instance.

If I understand you correctly, in your setup for some reason the subscriber in the test environment sends a subscribe message to the production publisher. By default, if no catalog overrides are provided, the subscription message is sent to the queue table in the same catalog. 

> When database Foo gets refreshed into test

What do you mean?

Can you open a support case and include the configuration of both publisher and the subscriber?

**Comment by markgould** [comment]
Sorry, I should have been more clear. Fairly often a backup of the production environment is restored as the test database, which I'm sure is not that uncommon. 

Because the sql transport does not support pub/sub, sql persistence handles the subscription storage, so the subscription data is stored with the business data.

So when an event is then published from the test system, both the test and production subscribers receive the event. 

A workaround would be for us to clear the subscription tables after restoring the database, or just do a replace with the test catalog name. 

I can submit the configuration, but it is quite basic.

**Comment by SzymonPobiega** [comment]
@markgould if we allowed using a separate catalog for subscription data would this solve your problem? Then you would only back up your data/sagas DB and restore it in the test environment. The subscriptions would remain intact.

**Comment by markgould** [comment]
That would be perfect!

**Comment by markgould** [comment]
#373 would also do what I need. Not sure how likely that is to happen though?

**Comment by SzymonPobiega** [comment]
@markgould I'd say it is going to happen for sure. The only question is when. I am flagging it now for the next maintenance release of SQL transport.

**Comment by markgould** [comment]
Now that https://github.com/Particular/NServiceBus.Persistence.Sql/issues/276 is complete, this should give me what I need. I can keep the subscriptions with my queue database, while leaving the saga with the business data.

**Comment by weralabaj** [comment]
@markgould Please, keep us updated if you hit any issues or have comments regarding usage scenarios/implementation details. Your feedback will be more than welcome :)
