### ISSUE TITLE
Make adding a computed column for viewing message body an opt-in

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#445]
The PR adding a computed column has been merged to develop, however, it should be a configurable opt-in. The goal is to add methods that allow to turn it on, it will be disabled by default.

- [x] Add info in doco (the feature hasn't been documented yet) https://github.com/Particular/docs.particular.net/pull/3861/commits/e1ee79a97436458fc956a81e1cd7df79b5112c1d

Based on [this comment](https://github.com/Particular/NServiceBus.SqlServer/pull/433#issuecomment-384830631) we might need to make this feature configurable to account for BOM or different encodings.

![image](https://user-images.githubusercontent.com/122666/39338794-736a1c2e-4a08-11e8-9e13-338054f16957.png)

**Comment by SimonCropp** [comment]
so in sql native i allowed people to override it https://github.com/NServiceBusExtensions/NServiceBus.Native/blob/288e507e930a228e0d858d6d722b1a13816d5d7e/SqlServer.Native/BaseQ/BaseQueueManager_QueueCreator.cs#L34
