### ISSUE TITLE
Max message size

### ISSUE THREAD

**Issue by Tobias-Gr** [Particular/NServiceBus.SqlServer#464]
Hi,

do you have any advice/documentation regarding large messages in SQL Transport? We have to handle/pass along large documents (a few KB up to several MB) with the messages.

The technical maximum is 2 GB in my understanding. But what are the implications of larger messages in SQL Transport? Do you have any experience? What might be reasons to better use the Databus feature?

Thanks!
Tobias

**Comment by mauroservienti** [comment]
Hi @Tobias-Gr,

thanks for raising this. Large messages are problematic regardless of the way you handle them, either storing them entirely in the transport, as allowed by SqlTransport, or via the DataBus feature.
In both cases when the message is received and deserialization happens the whole message has to be loaded into memory, causing a lot of memory pressure on the endpoint process and on the database, if storing the whole message there, or a lot of I/O pressure is using the DataBus, for example via a shared network location.

A better option, if suitable in your scenario, could be to leverage something like [SQL Attachments](https://docs.particular.net/nservicebus/messaging/attachments-sql) that allows you to have full control over the large payload life-cycle.

**Comment by Tobias-Gr** [comment]
Hi @mauroservienti ,
thanks! The main difference of SQL Attachments compared to Databus is that it's stream based and should use less ressources and be more scalable. Correct?
I know that it's a community project but do you have any experience in production use of SQL Attachments?

**Comment by mauroservienti** [comment]
> thanks! The main difference of SQL Attachments compared to Databus is that it's stream based and should use less ressources and be more scalable. Correct?

Correct. The important thing is that it's your code that decides when to open and read the stream.

> I know that it's a community project but do you have any experience in production use of SQL Attachments?

Not specifically with that package.

**Comment by Tobias-Gr** [comment]
OK, thanks!
