### ISSUE TITLE
Dispose the connection prior to processing the message in TransactionScope mode

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.SqlServer#465]
ie why this
```
using (var scope = new TransactionScope(TransactionScopeOption.RequiresNew, transactionOptions, TransactionScopeAsyncFlowOption.Enabled))
using (var connection = await connectionFactory.OpenNewConnection().ConfigureAwait(false))
{
    message = await TryReceive(connection, null, receiveCancellationTokenSource).ConfigureAwait(false);

    if (message == null)
    {
        // The message was received but is not fit for processing (e.g. was DLQd).
        // In such a case we still need to commit the transport tx to remove message
        // from the queue table.
        scope.Complete();
        return;
    }

    connection.Close();

    if (!await TryProcess(message, PrepareTransportTransaction()).ConfigureAwait(false))
    {
        return;
    }

    scope.Complete();
```

instead of this

```
using (var scope = new TransactionScope(TransactionScopeOption.RequiresNew, transactionOptions, TransactionScopeAsyncFlowOption.Enabled))
{
    using (var connection = await connectionFactory.OpenNewConnection().ConfigureAwait(false))
    {
        message = await TryReceive(connection, null, receiveCancellationTokenSource).ConfigureAwait(false);

        if (message == null)
        {
            // The message was received but is not fit for processing (e.g. was DLQd).
            // In such a case we still need to commit the transport tx to remove message
            // from the queue table.
            scope.Complete();
            return;
        }
    }

    if (!await TryProcess(message, PrepareTransportTransaction()).ConfigureAwait(false))
    {
        return;
    }

    scope.Complete();
}
```

**Comment by SzymonPobiega** [comment]
Hmm I am a bit confused. You are asking why the connection is closed before the message is processed?

**Comment by SimonCropp** [comment]
wondering why we close before the message processing, then dispose after message processing

**Comment by SzymonPobiega** [comment]
That's a good question. I think it could be disposed immediately after receiving. I think that "adding early close" was the easiest thing that could be done at some point.

**Comment by SimonCropp** [comment]
the reason i am asking is i am trying to debug a nested connection issue causing an escalation to DTC. when looking i found this code and though it was problematic. arguably the connection should be disposed asap so it can be returned to the pool?

**Comment by SzymonPobiega** [comment]
Not sure about returning to the pool but closing is enough to not trigger escalation. This is used when SQLT works with NH persistence. They both share the `TransactionScope` but use their own connection without causing escalation.

**Comment by SimonCropp** [comment]
> Not sure about returning to the pool but closing is enough to not trigger escalation.

yep, this was not the cause of my DTC escalation. DTC escalation was just the reason i was looking at the code. but dispose clearly does more cleanup than close, so should be done prior to message processing?

**Comment by SzymonPobiega** [comment]
@SimonCropp yeah. I believe so. No reason to not dispose it.

**Comment by SimonCropp** [comment]
perhaps re-title?
