### ISSUE TITLE
At TransactionLevel.None header manipulations done while processing a message are visible in recoverability policy

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#467]
When a header is added/deleted/modified in an attempt to process a message and that attempt fails, these header manipulations are visible when the recoverability policy is executed to determine if/how the message should be retried.

**Comment by SzymonPobiega** [comment]
The potential solution would be to copy the headers before passing them to the handler. Because non-transactional mode's only purpose is to allow high throughput, making a copy of each message headers dictionary sounds like a bad idea. 

I would lean towards not doing anything and waiting for the Core to fix it. Thoughts @Particular/sqlserver-transport-maintainers ?

**Comment by tmasternak** [comment]
> I would lean towards not doing anything and waiting for the Core to fix it. 
Sounds good.
