### ISSUE TITLE
Application Name in connection string not used

### ISSUE THREAD

**Issue by gcmvanloon** [Particular/NServiceBus.SqlServer#500]
While debugging an issue with SQL Transport I noticed the `Application Name` in the connection string is not picked up by NServiceBus. I wanted to use the Application Name on order to filter the SQL Profiler results.
When using `transport.ConnectionString(someConnectionString)` the Application Name is ignored.
I ended up using a custom SQL connection factory in order to get the correct Application Name in SQL Profiler which does work ok. I think this should also work without using a custom factory...
Found in package NServiceBus.SqlServer 1.4.3

**Comment by WilliamBZA** [comment]
Are you able to create a repro for this?

I took the sample [here](https://docs.particular.net/samples/sqltransport/simple/) and added `Application Name=MyAppName` to the connection string and it showed up correctly as expected.

![image](https://user-images.githubusercontent.com/1060960/63579366-c440f800-c592-11e9-9994-a03d351e33e0.png)

**Comment by WilliamBZA** [comment]
Sorry, I just noticed the version number you are using. Version 1.4.3 is also no longer supported, so there won't be any changes made to that version anymore.

You can see a list of the Sql Packages and what versions are supported [here](https://docs.particular.net/nservicebus/upgrades/supported-versions#transport-packages-nservicebus-sqlserver)
