### ISSUE TITLE
No delay when moving matured delayed messages after exception

### ISSUE THREAD

**Issue by christoffer-rydberg** [Particular/NServiceBus.SqlServer#501]
I'm working in a project where our logs sometimes get spammed with "Exception thrown while performing cancellation". It happens in [DelayedMessageHandler](https://github.com/Particular/NServiceBus.SqlServer/blob/54fadb504f3b0752c748010e51504cb62bf54b38/src/NServiceBus.SqlServer/DelayedDelivery/DelayedMessageHandler.cs#L63) when the sql transaction commit throws an exception. This results in tens of thousands of log messages. The issue seems to be that the while loop continues without delay.

**Comment by dvdstelt** [comment]
We have prioritized your issue near the top of our list and will be working on it as soon as we can.

**Comment by danielmarbach** [comment]
Will be contained in 4.3.1 that is going to be released soonish

**Comment by danielmarbach** [comment]
Released the new version https://discuss.particular.net/t/nservicebus-sqlserver-4-3-1-patch-release-available/1437
