### ISSUE TITLE
Purging Expired Messages

### ISSUE THREAD

**Issue by mtcoope** [Particular/NServiceBus.SqlServer#505]
We are currently using the SQL transport and having some performance issues on our database. We noticed that the current purge is an area where we noticed poor performance. I was wondering if there was a reason it is being done this way.

```
public static readonly string PurgeBatchOfExpiredMessagesText = @"
DELETE FROM {0}
WHERE RowVersion
    IN (SELECT TOP (@BatchSize) RowVersion
        FROM {0} WITH (READPAST)
        WHERE Expires < GETUTCDATE())";
```

Would we see performance gains from using a where exists? 

```
DELETE
FROM {0}
WHERE EXISTS 
   ( 
   SELECT TOP (@BatchSize) 1  
   FROM {0} m1
   WITH  (NOLOCK)  
   WHERE Expires < GETUTCDATE() 
       AND m1.[RowVersion] = [RowVersion]
   )  
```

Thanks

**Comment by SzymonPobiega** [comment]
@mtcoope I am not sure by looking at the query which one would be better but we did notice performance problems with the purging behavior and in the most recent versions of SQL Server transport expired message purging is an opt-in feature that has to be explicitly enabled.

By default it is not used as the assumption is that vast majority of messages is processed within their allocated TTL and is makes more sense to discard the ones that are expired after receiving them.

**Comment by SzymonPobiega** [comment]
The new releases of SQL transport don't use the expired message purger process.
