### ISSUE TITLE
Inconsistent Startup Behaviour when SQL Server is down

### ISSUE THREAD

**Issue by gbiellem** [Particular/NServiceBus.SqlServer#517]
When an endpoint is running SQL becomes unavailable the circuitbreaker is armed and after some retries the endpoint is shutdown.  This is the behavior I'd expect. 👍 

However,  if an endpoint is restarted while SQL is down the circuit breaker is not armed,  and it depends on configuration side effects as to whether the endpoint is taken down or just continues to retry forever.   

Our production endpoints run as Windows Services.  These are configure to restart on failure a couple of times and then give up .   When SQL is down what we are seeing is a service restart and then our
logging server is flooded with retry messages until SQL becomes available again.  

Here is a [repro](https://github.com/gbiellem/SqlTransportStartupRepro) based on the current docs SQL transport sample that doesn't exit when SQL is unavailable at startup.  It exhibits the same behavior we are seeing.

Obviously we can mitigate this by introducing our own checks at startup but that seems like a hack to get around the current inconsistent behavior

**Comment by gbiellem** [comment]
For your amusement, here's  a view from the SEQ logging server during the outage that led me to raise this issue.   All of these are SQL Transport error at the "Fatal" logging level

![image](https://user-images.githubusercontent.com/2351700/67536510-4aa8c000-f723-11e9-924c-b6a584a2b7c5.png)

**Comment by gbiellem** [comment]
Did some digging.  One of the reasons the behavior is inconsistent based on config is in the CheckForAmbientTransactionEnlistmentSupport method.  Depending on the transaction mode this [line](https://github.com/Particular/NServiceBus.SqlServer/blob/6ae38349c273ddf416bb465478975e8f8d703a24/src/NServiceBus.SqlServer/SqlServerTransportInfrastructure.cs#L187) is executed and throws if SQL is down taking down the endpoint.

**Comment by danielmarbach** [comment]
@gbiellem thanks for raising the issue. 

Is it correct to say your expectation would be that when we start and SQL is down you would like to see the endpoint throwing and the exception that is thrown should be consistent across all transport transactions?

The problematic behavior, if I understood you correctly, is that in some cases when the `CheckForAmbientTransactionEnlistmentSupport ` is NOT executed there will be no exception when the SQL Server is down and it will stay alive but constantly flood the logs with fatal?

Are there any other operational consequences you see from this inconsistency other than "log flooding"? I don't mean this in a derogative way. I would like to better understand whether we have a bug here or more on an improvement type of issue. And if we end up treating this as a bug what the priority of this should be.

**Comment by danielmarbach** [comment]
On another note, the linked repo https://github.com/gbiellem/SqlTransportStartupRepro is down. I'm guessing for anyone to repro this it would be enough to take the sql sample and start it with shut down sql server?

**Comment by gbiellem** [comment]
Sorry @danielmarbach  I forgot to make the repo public... fixed

**Comment by gbiellem** [comment]
>Is it correct to say your expectation would be that when we start and SQL is down you would like to see the endpoint throwing and the exception that is thrown should be consistent across all transport transactions?

Yes,  That's my expectation.  I would have expected an infrastructure outage that causes a service to crash would not allow that service on restart to appear to be running fine but in reality be  in a perpetual state of retry which is what is happening now.  I mentioned the logging aspect but from a monitoring aspect it is also bad, since tools that report on the Windows service state will report the service as being up and running

**Comment by gbiellem** [comment]
> And if we end up treating this as a bug what the priority of this should be.

It's easily mitigated in client code so at a minimum I suggest add some doco on this. our workaround was to add a check prior to endpoint startup to check we can open a sql connection and fail if it times out

**Comment by gbiellem** [comment]
> I'm guessing for anyone to repro this it would be enough to take the sql sample and start it with shut down sql server?

Yep after you strip out the queue creation etc and change the transaction mode

**Comment by danielmarbach** [comment]
@gbiellem other than aligning the behavior I'd be curious what CriticalErrorAction you have defined? In NSB v7 the default critical action is empty. If a critical error action is defined then under all the other transport transaction modes that don't fail the startup check it would eventually trigger the circuit breaker and the critical action. So if you add environment failfast to the critical action as defined by https://docs.particular.net/nservicebus/hosting/critical-errors#custom-handling-a-possible-custom-implementation then it would shut down your service. In that case the thing that is left is the inconsistency between the transport transaction mode.

But I'm guessing checking if we can actually establish a connection before we start makes sense under the light that we also have to check the transaction support (which requires a connection to be opened)

**Comment by danielmarbach** [comment]
Labeled this as a bug for now. Will follow up with the next steps once they have been discussed. It might take a while.

**Comment by danielmarbach** [comment]
@gbiellem sorry I should have asked earlier but forgot. On which version of the transport are you running?

**Comment by gbiellem** [comment]
>  On which version of the transport are you running?
4.3.1

> I'd be curious what CriticalErrorAction you have defined
Yes we do.  It basically flushes the logs and calls FailFast

The circuit breaker never arms or kicks in though since the  endpoint never finishing starting.
It's appears to be stuck looping in the MoveMaturedDelayedMessages method in the DelayedMessageHandler,   I believe the exception logic in that while loop is the problem.. 

https://github.com/Particular/NServiceBus.SqlServer/blob/6ae38349c273ddf416bb465478975e8f8d703a24/src/NServiceBus.SqlServer/DelayedDelivery/DelayedMessageHandler.cs#L57-L66

On startup a SqlException is being thrown but Cancellation hasn't been requested to it's falls through to the next case which logs the message we are getting and the exception is swallowed and So the loop continues and never returns.  Shouldn't that code also interact with the circuitbreaker like the message dispatcher does.

**Comment by gbiellem** [comment]
@danielmarbach  Simon and I did a bunch more testing/debugging today.  Seems the service is dying correctly on startup (We had a red herring of a different code path when running as a console app) but we do end up with a lot of logging from the code I highlighted.  This makes this way less of an issue in regard to monitoring but still a PITA from a logging perspective.  A single endpoint is generating 10Mb of logs when the endpoint is started and then SQL is stopped.  This is with the service set to two restarts.  Interestingly 90% of the of the logging is from the install loss of  connection not the restarts

**Comment by gbiellem** [comment]
Interestingly the delay in that loop is a second but the log entries are showing the FTL messages are 2ms apart.

```
2019-10-29 16:40:30.402 +11:00 [FTL] Exception thrown while performing cancellation
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (2): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at NServiceBus.Transport.SQLServer.SqlConnectionFactory.<>c__DisplayClass2_0.<<Default>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NServiceBus.Transport.SQLServer.SqlConnectionFactory.OpenNewConnection()
   at NServiceBus.Transport.SQLServer.DelayedMessageHandler.MoveMaturedDelayedMessages()
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20
2019-10-29 16:40:30.404 +11:00 [FTL] Exception thrown while performing cancellation
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (2): The system cannot find the file specified
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at NServiceBus.Transport.SQLServer.SqlConnectionFactory.<>c__DisplayClass2_0.<<Default>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NServiceBus.Transport.SQLServer.SqlConnectionFactory.OpenNewConnection()
   at NServiceBus.Transport.SQLServer.DelayedMessageHandler.MoveMaturedDelayedMessages()
ClientConnectionId:00000000-0000-0000-0000-000000000000

```

**Comment by gbiellem** [comment]
I've retested with 4.3.1 and all is good.   Seems you guys fixed it here -> https://github.com/Particular/NServiceBus.SqlServer/pull/509

So it seems we need to ensure we update all endpoints to 4.3.1 to avoid the log noise.

Thanks @danielmarbach and apologies for giving you the runaround when it was us not keeping up to date and tripping over our own red herring

**Comment by danielmarbach** [comment]
@gbiellem All good, nothing to apologize. If any then it would have to be me because I should have asked earlier what version you are on. Once I saw you mentioning the `MoveMaturedDelayedMessages ` I was like "oh I we fixed that one" but until I was able to comment you already noticed that it was fixed. Thanks for the patience with me!
