### ISSUE TITLE
Consider turning off auto statistics for the SqlServer transport

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.SqlServer#53]
Raised by @andreasohlund
Migrated from by https://github.com/Particular/NServiceBus/issues/1127

Since the "queue" tables will be mostly empty auto statistics might be more harmful than good

We can turn it off when creating the table:

http://msdn.microsoft.com/en-us/library/ms188775.aspx

**Comment by SimonCropp** [comment]
@andreasohlund still want to pursue this?

**Comment by andreasohlund** [comment]
Still relevant but not a high prio. Perhaps we should just add it to http://docs.particular.net/nservicebus/sqlserver/operations-scripting ? 

Ie add `SET AUTO_CREATE_STATISTICS OFF`

**Comment by SimonCropp** [comment]
@andreasohlund this might not be a high prio, but isnt it a trivial change?

**Comment by andreasohlund** [comment]
Indeed, but the testing effort wouldn't be trivial so that's why I haven't
done it yet
