### ISSUE TITLE
SqlServer transport should have a DLQ table

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus.SqlServer#6]
Messages that can't be delivered should be sent to the DLQ

@andreasohlund any other situations?

**Comment by mauroservienti** [comment]
@tmasternak do you value in this? shall we re-open it and consider it for a minor release of vNext?

**Comment by tmasternak** [comment]
@mauroservienti no. With the current approach to multi-db in v3 I can't think of any use case that would take advantage of DLQ.

**Comment by mauroservienti** [comment]
on a broker, such as SQL, what happens if we try to **publish** to a non existing queue?
Sending to a non existing queue will raise an exception at the sender, so that's not an issue.

**Comment by tmasternak** [comment]
That's correct. When queue does not exist exception will be thrown. If the send originated from handler that will most likely result in message being moved to errors. If the send is done outside of handler it's user responsibility to handle that.

**Comment by mauroservienti** [comment]
> what happens if we try to **publish** to a non existing queue?

**Comment by tmasternak** [comment]
I think that publish and send will behave the same for SqlServer transport.

**Comment by mauroservienti** [comment]
OK, if that's the case we don't need to support DLQs

**Comment by andreasohlund** [comment]
What if the headers are corrupt?

**Comment by tmasternak** [comment]
> What if the headers are corrupt?

If by corrupt you mean not possible to deserialize than the exception will be returned to the sender just like in other cases.

**Comment by andreasohlund** [comment]
I mean what if someone, eg doing native integration - http://docs.particular.net/nservicebus/sqlserver/operations-scripting, sticks invalid headers into the headers column? or runs some script that corrupts them?

**Comment by tmasternak** [comment]
If there is a row in the table that we are able to query on the ado.net level but unable to [pare the results](https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Queuing/TableBasedQueue.cs#L51). We treat that as poison message and move it immediately to error queue.

**Comment by andreasohlund** [comment]
Ah, yes that will cover it, thanks!

**Comment by ramonsmits** [comment]
Just had a conversation with @MarcinHoppe and IMHO we should not DELETE expired message but move them to a dead-letter queue (DLQ).

We should reevaluate this.

The current implementation of just ignoring the message removes traceability and auditing.

**Comment by andreasohlund** [comment]
>but move them to a dead-letter queue (DLQ).

this is exactly what MSMQ is doing if the DLQ flag is on (we have it on by default in NSB)

**Comment by MarcinHoppe** [comment]
@ramonsmits @andreasohlund I guess ops people are used to periodically cleaning up MSMQ DLQ. We'd have to educate them to set up SQL Agent jobs (or something) to clean up the DLQ. Just a thought.

**Comment by mauroservienti** [comment]
> I guess ops people are used to periodically cleaning up MSMQ DLQ. We'd have to educate them to set up SQL Agent jobs (or something) to clean up the DLQ. Just a thought.

Or do this https://github.com/Particular/ServiceControl/issues/63

**Comment by ramonsmits** [comment]
@mauroservienti That is an awesome feature to add to SC/SP in the future.

Still, in regards to the SQL transport I think it would be nice to add this as at least an option to enable DLQ. Maybe add it as minor release as deleting message does not feel as the correct thing. Maybe if the user wants a DLQ that it would be a good nudge to move to a different transport.

**Comment by mauroservienti** [comment]
We just had an interesting discussion during the sync related to DLQ, let's re-open this. Tomorrow morning I'll take care of raising more issues and linking this.

**Comment by MarcinHoppe** [comment]
@mauroservienti @ramonsmits @andreasohlund @tmasternak @johnsimons I'm calling out all the people who chimed in on this issue:

Do you still think we should have this discussion? If you do, please comment here.

If not, I will close the issue on November 1st, 2016.

/cc @Particular/sqlserver-transport-maintainers

**Comment by ramonsmits** [comment]
I think DLQ is important but maybe this needs to be discussed in the context of what to do with that data. For SQL message could be pushed to a service control like endpoint, for MSMQ we might need host important pushed that data there, etc. 

If we don't have a vision yet about how to manage those DLQ messages on an operational level than I think we cannot continue this discussion.

**Comment by mauroservienti** [comment]
I fully support what @ramonsmits said. We need a direction and alignment across transports, otherwise it might be a sort of a waste.

**Comment by SzymonPobiega** [comment]
Closing in favour of PlatDev version of it https://github.com/Particular/PlatformDevelopment/issues/1069. Without ability to specify poison message queue in the endpoint config, we can't do much at the transport level.
