### ISSUE TITLE
SQL Server transport 3.x refuses to process messages if there are too many messages in the queue

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.SqlServer#605]
The bug in https://github.com/Particular/NServiceBus.SqlServer/issues/481 was fixed in [SQL Server Transport 4.1.2](https://github.com/Particular/NServiceBus.SqlServer/releases/4.1.2) but that change was not backported to 3.1.x which is [still supported until 2020-05-29](https://docs.particular.net/nservicebus/upgrades/supported-versions#transport-packages-nservicebus-sqlserver).

### Symptoms

* The endpoint times out while peeking at the queue and receives no messages to process even though many messages exist
* An endpoint hangs while attempting to start it

### Who's affected

All users of SQL Server Transport 3.x (for NServiceBus 6.x) if the queue length gets too long.

### Root cause

SQL Server transport uses a periodic `select count(*)` query to asses how many messages is there in the queue to know how many receive tasks to spawn. If there is too many messages in the queue, `select count(*)` becomes a very slow operation requiring a table/index scan. It can easily take longer than 30 seconds in which case the operation times out and no messages are received.

**Comment by Yunhan-Zheng** [comment]
Hi David, 
This is Yunhan who submitted the support ID 00053419. 
We current still see all of our endpoints with long running peek statement UP in prod. 
I'm waiting for the DBA team to add more info on the database health condition.
BTW, do you suggest we kill those long running Peek queries in Prod? Will that cause endpoints to go down?

**Comment by DavidBoike** [comment]
I would not kill them. That could lead to the endpoint tripping its circuit breaker and eventually stopping. I would make sure you are on the latest version of ServiceControl and ServiceControl Monitoring, if you use them, because those also have to fetch the queue length of their input queues (error and audit) and get the queue length to display in the monitoring. Also I would ask the database team if there’s anything that can be done for that query (reindexing, etc) that would make it more likely that query can execute successfully and quickly.

Also, what is the approximate queue length on the endpoints where you’re having trouble?

**Comment by Yunhan-Zheng** [comment]
The endpoints that have really long running peek queries (started two weeks ago) don't have any messages in the queue now. All of those queries have status sleeping and no blocking session with them.

**Comment by DavidBoike** [comment]
That sounds like a good state. If those queues stay empty-ish, you might not have any problems. The bug has been prioritized and we'll be working on it soon.

**Comment by Yunhan-Zheng** [comment]
In the receiver side, we've seen a lot warning messages https://github.com/Particular/NServiceBus.SqlServer/issues/422, Is this https://github.com/Particular/NServiceBus.SqlServer/issues/422#issuecomment-455307379 worth trying in NSB6?

**Comment by DavidBoike** [comment]
@Yunhan-Zheng it's worth a shot. if it doesn't help the system any it's easy to revert with no harm done.

**Comment by WojcikMike** [comment]
This problem was fixed as a part of 3.1.6 release.
