### ISSUE TITLE
ExpiredMessagesPurger initialized and connecting to storage even though its disabled

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.SqlServer#610]
While diagnosing customer issue the customer reported that they saw log events from `ExpiredMessagesPurger` while cleanup was disabled. Not only was it writing log entries but also connecting to storage which is not expected for a feature that is disabled

Source: https://discuss.particular.net/t/more-log-messages-after-moving-to-nservicebus-extensions-logging/1727/5

**Comment by danielmarbach** [comment]
Fixed and improved as part of https://github.com/Particular/NServiceBus.SqlServer/pull/662. Will be available in the next patch release
