### ISSUE TITLE
UseCustomSqlTransaction(...) extension method for PublishOptions

### ISSUE THREAD

**Issue by Thorarin** [Particular/NServiceBus.SqlServer#622]
The SQL Server transport package includes the extension method `SendOptionsExtensions.UseCustomSqlTransaction`. For consistency, I think the same extension method should  be offered for **`PublishOptions`** as well as `SendOptions`.

#### Rationale

1. Consistency of the API (like I already mentioned)

2. Help customers not shoot themselves in the foot (1)
  I initially rolled my own similar method based on the `update-and-publish_router_3` sample. 
  Unfortunately I forgot to cast my `DbTransaction` to a `SqlTransaction`, which basically makes the 
  whole thing a no-op.

3. Help customers not shoot themselves in the foot (2)
  The sample code I found would not work in newer projects using **`Microsoft.Data.SqlClient`** instead of `System.Data.SqlClient`. The extension method solves this by using hard-coded keys for the ContextBag, but these constants are not available from the outside. They have to be gleaned from GitHub sources 😉 A simple extension method would solve this problem.

**Comment by SzymonPobiega** [comment]
Hi @Thorarin . I agree. We are making this as a candidate for next enhancement release which is going to happen soon.
