### ISSUE TITLE
Discrepancy between documentation and code for Index_RowVersion

### ISSUE THREAD

**Issue by mlalevic** [Particular/NServiceBus.SqlServer#642]
I'm using SQL transport 6.1, my endpoint is warning me that: Table ... does not contain non-clustered index 'Index_RowVersion'

When I look at documentation - suggested installation script is creating that index as clustered. https://docs.particular.net/transports/sql/sql-statements

CREATE CLUSTERED INDEX Index_RowVersion ON {0}
(
    RowVersion
)

This is confusing, so should the index be non clustered? and are there other changes required to that installation script?

**Comment by ramonsmits** [comment]
@mlalevic In the latest release it got changed to non clustered. It might be that we've missed a piece of documentation.

**Comment by ramonsmits** [comment]
@mlalevic Thanks for the feedback, I've updated the docs: https://github.com/Particular/NServiceBus.SqlServer/issues/642
