### ISSUE TITLE
Make the Id column a string instead of `UniqueIdentifier`

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.SqlServer#74]
Since the core only needs a string.

Also modify it to be optional since message id is included in the headers anyway.

So the logic in v6 would be: (where the core requires the transport to return a MessageId)

If Id column is not null, return `Id. Else return RowVersion + table name, eg `123-Sales`

**Comment by andreasohlund** [comment]
I think it still relevant. Since the core is just requiring a string we should:

1. Make the column and IDENTITY to make it easier for native integrations to insert into it
2. Return "TableName-value" to the core (the core uses that ID if the message has no MessageID header) The reason to put the table name is to make it globally unique.

Perhaps this should be in a different issue?

**Comment by tmasternak** [comment]
@andreasohlund ok so the argument here is native integration right?

**Comment by andreasohlund** [comment]
>ok so the argument here is native integration right?

Yep

**Comment by andreasohlund** [comment]
Actually, it think we should make it an identity instead since we want it to be autoincremented and performant? (I'll update the description if we agree)
