### ISSUE TITLE
DueDelayedMessageProcessor is missing circuit breaker

### ISSUE THREAD

**Issue by mikeknoll** [Particular/NServiceBus.SqlServer#744]
When SQL becomes unavailable, queue peeking and receiving's tasks trip a circuit breaker, reducing load and repetitive logging.  

However, DueDelayedMessageProcessor continues to retry at the same interval, increasing load and producing excessive logging.  It appears that it would be beneficial to add a circuit breaker to DueDelayedMessageProcessor.

**Comment by DavidBoike** [comment]
Hey @mikeknoll. I've triaged this issue and it seems like something that might get rolled into our next SQL Transport enhancement release.

Am I correct in assuming that this isn't causing any issues with correctness, but it's primarily an annoyance whenever SQL becomes unavailable?

**Comment by mikeknoll** [comment]
It's not an issue of correctness.  

But, it can be more than an annoyance.  We've had issues in the past with excessive logging affecting system performance.

**Comment by danielmarbach** [comment]
Addressed by https://github.com/Particular/NServiceBus.SqlServer/pull/805

**Comment by danielmarbach** [comment]
Will be released and addressed as part of the next major version.
