### ISSUE TITLE
DueDelayedMessageProcessor continues to execute when endpoint fails to start

### ISSUE THREAD

**Issue by mikeknoll** [Particular/NServiceBus.SqlServer#745]
When StartableEndpoint.Start() is called, DueDelayedMessageProcessor is started early, at transportInfrastructure.Start().  If SQL is unavailable at startup, an exception is thrown during startup, in receiveComponent.PrepareToStart(), when the MessagePump.Init() calls PurgeExpiredMessages(). The endpoint fails to start, but DueDelayedMessageProcessor continues to run, creating excess load and logging.

If an endpoint fails to start with StartableEndpoint.Start(), we would expect all endpoint tasks to be closed, setting us up to retry the StartableEndpoint.Start() later.

This is somewhat similar to https://discuss.particular.net/t/duedelayedmessageprocessor-prevents-delays-shutdown/2204.  We are running in a generic host, and calling IHostApplicationLifetime.StopApplication() does eventually stop DueDelayedMessageProcessor, but many executions go by before the clean up occurs, creating excess load and logging, at a time when the endpoint is thought to not be running.

**Comment by DavidBoike** [comment]
Hey @mikeknoll it sounds like similar to #744 this is an annoyance thing when SQL is unavailable. Could you confirm?

If so I would expect it to get swept up in the next enhancement release as well.

**Comment by mikeknoll** [comment]
They are similar issues, in that they both produce excessive logging.  #744 relates just to excessive executions.  This issue does produce excessive executions, but additionally, those executions are unexpected, as the endpoint is not in a started state.

**Comment by danielmarbach** [comment]
Addressed by https://github.com/Particular/NServiceBus.SqlServer/pull/805

**Comment by danielmarbach** [comment]
Will be released and addressed as part of the next major version.
