### ISSUE TITLE
Remove `ReplyToAddress` and `CorrelationId` columns

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.SqlServer#75]
Since they are transmitted as headers anyway

**Comment by tmasternak** [comment]
@andreasohlund @mauroservienti I think that this issue and 3 or 4 more all fall into "Enable schema changes keeping backward compatibility". This connects to #102. Should I close this one an the others and merge content to #102?

**Comment by andreasohlund** [comment]
I'm ok with that
