### ISSUE TITLE
Update queue creation scripts with fixed application locks release logic

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#757]
Entity creation scripts should properly [release the application lock](https://github.com/Particular/NServiceBus.SqlServer/blob/master/src/NServiceBus.Transport.SqlServer/Queuing/SqlConstants.cs#L166) when the creation script fails. 

Plan of Action
- [x] Update entity creation scripts in `SqlConstants.cs` https://github.com/Particular/NServiceBus.SqlServer/pull/861
- ~~Update native integration scripts in the doco~~ _These don't use the application lock, nor probably should they_
- [x] Update RuntimeScripts in the doco

**Comment by tmasternak** [comment]
Sorry for not being specific enough in the description. This issue is an outcome of the work done on the transport for the new seam. It looks that under higher load the system views that we use to figure out if a table, column, or index exists might be lagging behind reality. This in turn causes the script to fail and not releasing the application lock with `sp_release`. 

This has been already taken care of in master in this [commit](https://github.com/Particular/NServiceBus.SqlServer/commit/aad51da4ff275bd4d933718550ed1c89542fdc5c). This issue was meant to cover this scenario in the current releases. 

Side note. We did not treat this as an error as none of the clients reported any problems with this and we discovered that only under load testing.

**Comment by DavidBoike** [comment]
@tmasternak To be clear, was it only the changes in SqlConstants from https://github.com/Particular/NServiceBus.SqlServer/commit/aad51da4ff275bd4d933718550ed1c89542fdc5c that should be backported to the current version, or the whole commit?

**Comment by tmasternak** [comment]
@DavidBoike SqlConstants and the [try-catch with one additional case](https://github.com/Particular/NServiceBus.SqlServer/commit/aad51da4ff275bd4d933718550ed1c89542fdc5c#diff-ba5e3485de54263710e72268903d90bc151eb581604bbd0e6d865569f076cf28R59)

**Comment by DavidBoike** [comment]
Thanks @tmasternak - backported in https://github.com/Particular/NServiceBus.SqlServer/pull/861

**Comment by DavidBoike** [comment]
Released in SQL Transport 6.3.1
