### ISSUE TITLE
Body column size restriction can lead to indefinite retries

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.SqlServer#791]
The default value for the body column is `varbinary(max)`. It is possible to tweak this value. A customer has set it to `8kb`. During audit processing the message happened to become greater than `8KB`. When this happens Sql Transport cannot store the body, fails and after some retries tries to store the body into the error queue which had the same size restrictions. When that dispatch fails the transport indefinitely retries message over and over again. At least that happened in the specific cases with SQL transport running inside ServiceControl which then started to grow the DB size over time and made audit ingestion stall. 

I have not yet confirmed the behavior with a repro. Will do next week

**Comment by danielmarbach** [comment]
// cc @asopus

**Comment by dbelcham** [comment]
We've taken a look at this and decided this isn't a bug. The scripts output by the transport are correct and this problem would not happen if they were left un-modified. Our recommendation is to not modify the scripts in this manner, instead leaving them in their default state. Changing the modified columns back to the default settings will mitigate this problem going forward.
