### ISSUE TITLE
Send out a message from a handler even if the handler throws

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.SqlServer#80]
### Symptoms

Cannot send out a message if a handler execution ends with an exception.

### Who's affected

People who wish to send out messages even though the handler is throwing an exception in order to trigger the retry mechanism.

### Proposed solution

Store the original `Transaction` in the context and hook up to the receiving transaction only if the current transaction is same as the original. If not, create a separate connection.

### Original issue

The requirement is to be able to send out a message from a handler even if the handler throws an exception and goes to the retry cycle.

While the receiver has an ambient transaction strategy which creates a new `TransactionScope`, the `SqlServerMessageSender` is using the explicit connection created by the receiver and stored in the pipeline context.

Suppressing the transaction or requiring the creation of a new one do not produce the desired effect, the value of the `EnlistInReceiveTransaction`, of the `DeliveryOptions` class, is always set to `true`.

The same strategy worked well for us using MSMQ transport.

--

Desk Ref.: https://nservicebus.desk.com/agent/case/11144

**Comment by SzymonPobiega** [comment]
V6 code change will allow for that without changes to the transport.
