### ISSUE TITLE
Improve the delayed-delivery mechanism

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#804]
In the current approach, a delayed message is first moved to a dedicated table and when the delay time has elapsed it's moved back into the input queue of the sending endpoint. When such a message is received by an endpoint it's sent directly to the destination queue and not pushed through the pipeline.

The elapsed message could be moved directly to the destination queue (or to the error queue if the destination is unreachable).

**Comment by DavidBoike** [comment]
@tmasternak I'm confused on this one. The SQL for MoveDueDelayedMessageText is:

```sql
DECLARE @NOCOUNT VARCHAR(3) = 'OFF';
IF ( (512 & @@OPTIONS) = 512 ) SET @NOCOUNT = 'ON';
SET NOCOUNT ON;

WITH message AS (
    SELECT TOP(@BatchSize) *
    FROM {0} WITH (UPDLOCK, READPAST, ROWLOCK)
    WHERE Due < GETUTCDATE())
DELETE FROM message
OUTPUT
    NEWID(),
    NULL,
    NULL,
    1,
    NULL,
    deleted.Headers,
    deleted.Body
INTO {1};

IF (@NOCOUNT = 'ON') SET NOCOUNT ON;
IF (@NOCOUNT = 'OFF') SET NOCOUNT OFF;
```

So the ReplyToAddress in the Timeouts queue never gets added to the input queue. The headers and body just get dropped in the input queue with a new message id. It can't be "sent directly to the destination queue and not pushed through the pipeline" as stated in the issue description.

And thinking more generally, why would a delayed message ever be for anything other than the sending endpoint? Saga timeouts, delayed retries, and context.Defer() are all going to be for the current endpoint.

Is this issue invalid? Or am I missing something?

**Comment by tmasternak** [comment]
@DavidBoike let me try clarifying what I meant. What is currently happening when a message is delayed:
 1.  Header called `NServiceBus.SqlServer.ForwardDestination` holding the final destination of the delayed message is added.
 2. The message is stored in the `Delayed` table
 3. The message is picked up from the `Delayed` table when the delay elapses and moved back to the input queue of the sender
 4. If the sender detects the header it is [forwarded](https://github.com/Particular/NServiceBus.SqlServer/blob/master/src/NServiceBus.Transport.SqlServer/Receiving/ProcessStrategy.cs#L100) to the final destination.
  
This issue was meant to get rid of step 4 and move the message directly to the destination.

That said I agree that in the majority of cases a delayed message is destined to the originator and I'm not sure this is worth the effort tbh.

**Comment by DavidBoike** [comment]
Ah, I see how the forwarding works now.

But given that the due messages processor would have to stream the result set into memory, deserialize the headers, group by destination, and then dispatch messages (with the additional dependencies on the queue cache) … given that right now this happens server-side in a single query I find it really hard to justify that too.

**Comment by tmasternak** [comment]
@DavidBoike agreed.
