### ISSUE TITLE
missing NServiceBus.Core dependency on 1.2.3

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.SqlServer#91]
[Version 1.2.3](https://www.nuget.org/packages/NServiceBus.SqlServer/1.2.3) of the SqlServer package misses dependencies to NSB.Core which seem to be removed by accident while previous patch versions of the package still have the dependency.

**Comment by ramonsmits** [comment]
+1 I just noticed it too on Nuget while downgrading.

**Comment by timbussmann** [comment]
fixed with hotfix 1.2.4
