### ISSUE TITLE
Add ability to store Body as text

### ISSUE THREAD

**Issue by pawelpabich** [Particular/NServiceBus.SqlServer#93]
It could be a config value.

**Comment by SzymonPobiega** [comment]
you mean, instead of `(n)varchar(MAX)`?

**Comment by pawelpabich** [comment]
at the moment it's s varbinary and I would like to have an option to use nvarchar.

**Comment by SzymonPobiega** [comment]
That would be tricky since our serializer abstraction uses `Stream`s which we convert later to `byte[]` when sending a message. So from the perspective of a transport a message body is an opaque string of bytes.

Not saying it cannot be done, can I ask why do you need it? Is it for convenience of being able to inspect the message bodies using standard SQL Server tooling?

**Comment by pawelpabich** [comment]
Re why, you guessed correctly. I mostly use Sql Transport over MSQM because it is more accessible and people know how to manage Sql Server infrastructure. The fact that body is binary makes them uneasy which is very unfortunate.

One more note, Sql Server 2016 allows search text columns that contain JSON directly from Sql so having this option would enable advance querying without having to decomposition the data into separate columns.

**Comment by SzymonPobiega** [comment]
@pawelpabich I've raised an issue in the core repo https://github.com/Particular/NServiceBus/issues/2977 because if we decide to implement it, it would have to be a change in the heart of NServiceBus.

**Comment by tmasternak** [comment]
I think that enabling such feature would be problematic from backwards compatibility perspective as well. V1 and V2 of SqlServer expect current version of table schema.

**Comment by tmasternak** [comment]
I [looks](https://github.com/Particular/NServiceBus/issues/2977#issuecomment-197227661) that for V6 we won't be able to support this feature. I'm closing this one for now and we can revisit it later.
