### ISSUE TITLE
Wire compatibility tests for sql transport

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#98]
We should have a set of wire compatibility tests for v1-v3 of sql transport. We might try to reuse what we have in ProductionTests (which test message patterns and the headers that enable them).

**Comment by SimonCropp** [comment]
the wire compat tests in ProductionTests are not "testing MSMQ". they are testing the message patterns and the headers that enable them

**Comment by tmasternak** [comment]
@SimonCropp thanks for pointing that out. Description changed.

**Comment by tmasternak** [comment]
This has been covered with SqlTransport Backwards Compatibility tests. See Particular/ProductionTests/pull/26 and Particular/ProductionTests/pull/27. 

Closing
