### ISSUE TITLE
Redesign the concurrency adaptation algorithm

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#99]
Redesign the scheduler so that it is based on peek-receive approach rather than success/failures counter.

**Comment by SzymonPobiega** [comment]
@tmasternak is this a right place to track this?

**Comment by tmasternak** [comment]
@SzymonPobiega I think it is a good place to do it

**Comment by kanpal** [comment]
Has this been addressed yet?

**Comment by SzymonPobiega** [comment]
@kanpal the redesign is happening as part of V6 NServiceBys/ V3 of SQL transport. Why is this redesign important for you?

**Comment by MarcinHoppe** [comment]
Should we close this then as there's no adaptive poller in V3 and we're not working on it for V2?

**Comment by SzymonPobiega** [comment]
@MarcinHoppe yes, closing it. It is implemented in V3 and V2 stays as is.

**Comment by kanpal** [comment]
@SzymonPobiega - We opened this ticket with AgWorks. We are waiting on this patch to move forward with the enterprise license that we had bought two years back, which we are yet to roll out in production. We are still using the older v3 with MSMQ.

**Comment by SzymonPobiega** [comment]
@kanpal as I suggested, you can go to V5 and use 2.0.x version of SQL Server transport (no adaptation there). Alternatively, if you are not in hurry, you can wait until V6 comes out where this problematic adaptation algorithm has been replaced by an approach similar to MSMQ where we use `Peek` in a tight loop to check if there are any waiting messages.

**Comment by SzymonPobiega** [comment]
@kanpal We've released beta version of SQL Server transport for NServiceBus 6 https://www.nuget.org/packages/NServiceBus.SqlServer/3.0.0-beta0001. It contains rewritten scheduling algorithm that should respond better to bursts in load.

**Comment by kanpal** [comment]
@SzymonPobiega Thanks. We'll check it out. I assume this will require us to move to NServiceBus v6.00, which in turn requires .NET framework 4.6.1? Trying to understand the minimum requirements.

**Comment by SzymonPobiega** [comment]
@kanpal  NSeriveBus 6 requires .NET 4.5.2

**Comment by kanpal** [comment]
@SzymonPobiega - I hate to tell after hours of struggling the latest v6 with Sql v3 to work, the system suffers from the same adaptive algorithm bug as before. Plus the module is very unstable.

**Comment by tmasternak** [comment]
@kanpal can you give us more details about the problematic behavior that you are experiencing? Are you referring to adaptive algorithm that adjust the number of receivers? What kind of stability problem do you experience?

**Comment by kanpal** [comment]
@tmasternak First of all, we dont see any improvement in the adaptive algorithm, in other words we still see the same issue where it does not pick up the messages at peak load (same original problem). Second of all, the upgrade from v5 to 6 didn't go smooth. I had to start the project from scratch.

**Comment by tmasternak** [comment]
@kanpal Adaptive algorithm has been removed in V3 of SqlTransport (version that runs with V6 of Core). Can you share more information/code about the problem so that we can reproduce it?
